### ISSUE TITLE
Broken recognition during the Heads step

### ISSUE THREAD

**Issue by maximumspatium** [Audiveris/audiveris#135]
As the title says, audiveris doesn't work after the latest changes in the development branch (ee9ee59adf4f35c8f53343435dd9bde57bed729c). I tried it with one of the supplied examples allegretto.png. That's what I'm getting after the Heads step:

```
INFO  [allegretto]                 BasicBook 270  | 1 sheet in /Users/maxim/Documents/Development/audiveris-ng/data/examples/allegretto.png
INFO  [allegretto]                 BasicBook 993  | Loaded image 1 2520x2183 from /Users/maxim/Documents/Development/audiveris-ng/data/examples/allegretto.png
INFO  [allegretto]                 ScaleStep 87   | Scale{line(2,3,4) interline(21,21,23) beam(12)}
INFO  [allegretto]            LinesRetriever 444  | Global slope: -0.00212
INFO  [allegretto]         ClustersRetriever 242  | Retrieved line clusters: 6 of size: 5 with interline: (21,21,23)
INFO  [allegretto]                 PeakGraph 181  | Systems: #1[1, 2] #2[3, 4] #3[5, 6]
INFO  [allegretto]             SystemManager 662  | Indentation detected for system#1
INFO  [allegretto]             SystemManager 745  | 1 part along 3 systems
INFO  [allegretto]             StemSeedsStep 91   | stem(2 max:4)
INFO  [allegretto]            BlackHeadSizer 99   | Spots black-head retrieval diameter: 18.9
INFO  [allegretto]            BlackHeadSizer 251  | Core black head count: 36 blackHead(width:24.8~0.4 height:22.9~1.4)
INFO  [allegretto]            BlackHeadSizer 256  | MusicFont{name:MusicalSymbols pointSize:83}
INFO  [allegretto]                 BeamsStep 89   | BeamDistance{count:27 mean:16.31 stdDev:6.92}
WARN  [allegretto]        AbstractSystemStep 201  | S1 java.lang.IllegalArgumentException: Width (25) and height (0) cannot be <= 0
java.lang.IllegalArgumentException: Width (25) and height (0) cannot be <= 0
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
        at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
        at org.audiveris.omr.ui.symbol.SymbolImage.<init>(SymbolImage.java:54)
        at org.audiveris.omr.ui.symbol.BasicSymbol.buildImage(BasicSymbol.java:154)
        at org.audiveris.omr.image.ShapeDescriptor.createTemplate(ShapeDescriptor.java:549)
        at org.audiveris.omr.image.ShapeDescriptor.<init>(ShapeDescriptor.java:120)
        at org.audiveris.omr.image.TemplateFactory$Catalog.buildAllTemplates(TemplateFactory.java:148)
        at org.audiveris.omr.image.TemplateFactory$Catalog.<init>(TemplateFactory.java:120)
        at org.audiveris.omr.image.TemplateFactory.getCatalog(TemplateFactory.java:90)
        at org.audiveris.omr.sheet.note.NoteHeadsBuilder.buildHeads(NoteHeadsBuilder.java:235)
        at org.audiveris.omr.sheet.note.HeadsStep.doSystem(HeadsStep.java:69)
        at org.audiveris.omr.sheet.note.HeadsStep.doSystem(HeadsStep.java:44)
        at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:199)
        at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:182)
        at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:220)
        at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:106)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:814)
        at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:802)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
INFO  [allegretto]                      Page 256  | 18 raw measures: [6 in system#1, 6 in system#2, 6 in system#3]
INFO  [allegretto]              SlursBuilder 156  | Slurs: 0
INFO  [allegretto]           SegmentsBuilder 114  | Segments: 58
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1278(0.576) s:3 S-69 Direction} } 13P P
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1282(0.532) s:3 S-91 Direction} pp
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1290(0.696) s:3 I-38 Direction} 1 2 cresc.
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1305(0.694) s:4 IS-43 Direction} cresc.
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1350(0.713) s:5 S-36 Direction} 4 2
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1353(0.666) s:5 S-61 Direction} PP
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1357(0.694) s:5 IS-43 Direction} cresc.
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1359(0.602) s:5 S-150 Direction} EI
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1361(0.670) s:5 S-35 Direction} 111
INFO  [allegretto]             SymbolsLinker 162  | No chord near direction SentenceInter{#1365(0.652) s:5 S-36 Direction} 4 2 3
INFO  [allegretto]                PageRhythm 377  | Range{1-18 ts:2/4 dur:1/2} guess:null
INFO  [allegretto]                  StepMenu 169  | End of sheet step PAGE
```
I've even deleted all configuration files and tried from a fresh clone. Still the same error. Other scores don't work, too...

**Comment by maximumspatium** [comment]
It looks like 863a02e175f50e446811d0d3c640d03bf3a91d2e causes the issue. Anything before it works as expected.

**Comment by Bacchushlg** [comment]
I have transcripted more than 10 scores with this version - it works fine for me. I'd even say very good!

Must be something special concerning your input file. Did you try other input files - especially those that had problems due to "wrong" note head sizes?

**Comment by maximumspatium** [comment]
> Must be something special concerning your input file.

I tried several input scores including ALL examples shipped with audiveris. None of them works in my Mac. I cannot speak for Windows/Linux because I don't have an access to either for the time being.

**Comment by Bacchushlg** [comment]
Courious... I'm working on a Window10 system...

**Comment by maximumspatium** [comment]
Just tried on Linux Fedora in VirtualBox and got the same result for the test scores...

**Comment by hbitteur** [comment]
I'm closing the issue now

**Comment by Bacchushlg** [comment]
I had disabled small head recognition - seems that this was the reason for me not getting the problem...
