### ISSUE TITLE
NullPointerException in SlursBuilder

### ISSUE THREAD

**Issue by JalonSolov** [Audiveris/audiveris#141]
This is in the Blue Skies.pdf I sent before.  Same exception is thrown on page 5.

INFO  [Blue Skies#3]                      Page 256  | 29 raw measures: [4 in system#1, 4 in system#2, 4 in system#3, 4 in system#4, 4 in system#5, 3 in system#6, 3 in system#7, 3 in system#8]
WARN  [Blue Skies#3]              SlursBuilder 170  | Error in SlursBuilder: java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.audiveris.omr.sheet.curve.ChordSplitter.injectStandardHeads(ChordSplitter.java:325)
	at org.audiveris.omr.sheet.curve.ChordSplitter.getAllPartitions(ChordSplitter.java:233)
	at org.audiveris.omr.sheet.curve.ChordSplitter.split(ChordSplitter.java:161)
	at org.audiveris.omr.sheet.curve.SlursBuilder.handleTieCollisions(SlursBuilder.java:861)
	at org.audiveris.omr.sheet.curve.SlursBuilder.buildSlurs(SlursBuilder.java:154)
	at org.audiveris.omr.sheet.curve.Curves.buildCurves(Curves.java:135)
	at org.audiveris.omr.sheet.curve.CurvesStep.doit(CurvesStep.java:53)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:822)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:810)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hbitteur** [comment]
The NullPointerException is now fixed in commit 29621cf243e5cc5ee52b10aea250722ad4f710c4
