### ISSUE TITLE
NullPointerException in SymbolFactory?

### ISSUE THREAD

**Issue by JalonSolov** [Audiveris/audiveris#142]
This is in the Blue Skies.pdf I sent:

INFO  [Blue Skies#4]           SegmentsBuilder 114  | Segments: 31
WARN  [Blue Skies#4]        AbstractSystemStep 201  | S2 java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.audiveris.omr.sheet.symbol.SymbolFactory.handleComplexDynamics(SymbolFactory.java:835)
	at org.audiveris.omr.sheet.symbol.SymbolFactory.lateChecks(SymbolFactory.java:241)
	at org.audiveris.omr.sheet.symbol.SymbolsStep.doSystem(SymbolsStep.java:111)
	at org.audiveris.omr.sheet.symbol.SymbolsStep.doSystem(SymbolsStep.java:51)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:199)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:182)
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:220)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:106)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:822)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:810)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hbitteur** [comment]
Bug fix in commit 798338c3c822b87d50ab1ab2e8ef9f1beeab40db
