### ISSUE TITLE
IllegalArgumentException in glyph evaluation

### ISSUE THREAD

**Issue by JalonSolov** [Audiveris/audiveris#144]
This is in the Blue Skies.pdf I sent:

WARN  [Blue Skies#6]            SymbolsBuilder 228  | Error in glyph evaluation java.lang.IllegalArgumentException: TIME_ZERO not allowed as TimeNumberInter shape
java.lang.IllegalArgumentException: TIME_ZERO not allowed as TimeNumberInter shape
	at org.audiveris.omr.sig.inter.TimeNumberInter.<init>(TimeNumberInter.java:72)
	at org.audiveris.omr.sig.inter.TimeNumberInter.create(TimeNumberInter.java:122)
	at org.audiveris.omr.sheet.symbol.SymbolFactory.doCreate(SymbolFactory.java:376)
	at org.audiveris.omr.sheet.symbol.SymbolFactory.create(SymbolFactory.java:178)
	at org.audiveris.omr.sheet.symbol.SymbolsBuilder.evaluateGlyph(SymbolsBuilder.java:226)
	at org.audiveris.omr.sheet.symbol.SymbolsBuilder.processClusters(SymbolsBuilder.java:350)
	at org.audiveris.omr.sheet.symbol.SymbolsBuilder.buildSymbols(SymbolsBuilder.java:164)
	at org.audiveris.omr.sheet.symbol.SymbolsStep.doSystem(SymbolsStep.java:103)
	at org.audiveris.omr.sheet.symbol.SymbolsStep.doSystem(SymbolsStep.java:51)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:199)
	at org.audiveris.omr.step.AbstractSystemStep$1.call(AbstractSystemStep.java:182)
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:220)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:106)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:822)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:810)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hbitteur** [comment]
Bug fix in commit c5ca4f116e3a919424a0749c49baf9418e516962
