### ISSUE TITLE
NullPointerException in StackTuner

### ISSUE THREAD

**Issue by JalonSolov** [Audiveris/audiveris#147]
Happens twice on Page 3 of Blue Skies.pdf, latest development branch code:

WARN  [Blue Skies#3]                StackTuner 96   | Error java.lang.NullPointerException: Null point argument checkConfig 
java.lang.NullPointerException: Null point argument
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.audiveris.omr.sheet.Skew.deskewed(Skew.java:114)
	at org.audiveris.omr.sheet.rhythm.MeasureStack.getXOffset(MeasureStack.java:1176)
	at org.audiveris.omr.sheet.rhythm.MeasureStack.getXOffset(MeasureStack.java:1211)
	at org.audiveris.omr.sheet.rhythm.MeasureStack.getXOffset(MeasureStack.java:1155)
	at org.audiveris.omr.sheet.rhythm.Slot.computeXOffset(Slot.java:751)
	at org.audiveris.omr.sheet.rhythm.Slot.<init>(Slot.java:136)
	at org.audiveris.omr.sheet.rhythm.SlotsBuilder.buildSlots(SlotsBuilder.java:421)
	at org.audiveris.omr.sheet.rhythm.SlotsBuilder.process(SlotsBuilder.java:236)
	at org.audiveris.omr.sheet.rhythm.StackTuner.checkSlots(StackTuner.java:147)
	at org.audiveris.omr.sheet.rhythm.StackTuner.check(StackTuner.java:111)
	at org.audiveris.omr.sheet.rhythm.StackTuner.process(StackTuner.java:91)
	at org.audiveris.omr.sheet.rhythm.PageRhythm.retrieveRangeDurations(PageRhythm.java:361)
	at org.audiveris.omr.sheet.rhythm.PageRhythm.process(PageRhythm.java:125)
	at org.audiveris.omr.sheet.rhythm.RhythmsStep.doit(RhythmsStep.java:137)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:822)
	at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:810)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hbitteur** [comment]
Sorry, this scan is of too bad quality: most staves have their left side cropped by image limits.
Please, rescan this sheet and then relaunch Audiveris on it.

**Comment by mustefan** [comment]
It happens a lot on whole file [rosini_000962.pdf](https://github.com/Audiveris/audiveris/files/2171493/rosini_000962.pdf)


`
WARN  [rosini_000962#4]		StackTuner 96   | Error java.lang.NullPointerException checkConfig 
java.lang.NullPointerException: null
        at org.audiveris.omr.sheet.rhythm.SlotsBuilder.computeNextTerm(SlotsBuilder.java:598)
        at org.audiveris.omr.sheet.rhythm.SlotsBuilder.buildSlots(SlotsBuilder.java:396)
        at org.audiveris.omr.sheet.rhythm.SlotsBuilder.process(SlotsBuilder.java:236)
        at org.audiveris.omr.sheet.rhythm.StackTuner.checkSlots(StackTuner.java:147)
        at org.audiveris.omr.sheet.rhythm.StackTuner.check(StackTuner.java:111)
        at org.audiveris.omr.sheet.rhythm.StackTuner.process(StackTuner.java:91)
        at org.audiveris.omr.sheet.rhythm.PageRhythm.retrieveRangeDurations(PageRhythm.java:360)
        at org.audiveris.omr.sheet.rhythm.PageRhythm.process(PageRhythm.java:125)
        at org.audiveris.omr.sheet.rhythm.RhythmsStep.doit(RhythmsStep.java:143)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:877)
        at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:865)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
INFO  [rosini_000962#4]              SlotsBuilder 401  | Stack#14 suspicious Slot{#2 xOffset=99 timeOffset=1/8 incomings=[#20982]}
`
