### ISSUE TITLE
installer fails with error

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#184]
I have created an installer using NSIS which works fine on my machine.
But a test on a different machine results in the following:

C:\Program Files (x86)\Audiveris\bin>Audiveris.bat
INFO  []                      Main 338  | Environment:
- Audiveris:    5.1.0:5ef61d51b
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 206  | CLI args: []
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:128)
        at org.audiveris.omr.sheet.BookManager.getInstance(BookManager.java:313)
        at org.audiveris.omr.Main.main(Main.java:140)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more

Has anybody an idea where I should look for the reason?

**Comment by hbitteur** [comment]
Check the log file for additional JAXB info which may not appear in event window

**Comment by maximumspatium** [comment]
I suspect you're trying to run Audiveris under Java 9 which doesn't include JAXB in the standard edition (JAXB was moved to Enterprise Edition starting with Java 9).
You'd need to downgrade to JRE 8.

**Comment by hbitteur** [comment]
I just stumbled on this:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/46455026

**Comment by maximumspatium** [comment]
Yes, the issue has been properly fixed in the `java9` branch, see a9985adcd334c7294610863d9b18a08a2fd5897b
The real problem is that Audiveris won't work properly with Java 9, even with that JAXB issue fixed. We have to stick with Java 8.

**Comment by Bacchushlg** [comment]
Yes, that was the reason.

The installed version works fine with Java 8. Perfect!

What is curious: I have both versions (8 and 9) on my machine. For some 
reason Audiveris takes the "better" one automatically...

Where shall I put the installer? Also upload to GIT?

Or we can stay with the "private" version until we decide to publish the 
version.



Am 05.07.2018 um 20:54 schrieb Maxim Poliakovski:
