### ISSUE TITLE
Instalation stops on  Executing test org.audiveris.omr.util.BrokenLineTest

### ISSUE THREAD

**Issue by elacusta** [Audiveris/audiveris#197]
Hello,
I'm facing the following problem trying to install the program on Linux Mint: It keeps working forever at the testing phase at 81%. I've seen a closed request on the same issue, but no instructions to solve the problem.
Below, the gradlew screen, my java version and my gradle version.

many thanks
Eduardo

elacusta@elacusta-HP-Pavilion-dm1-Notebook-PC:~/audiveris$ sudo ./gradlew build

> Configure project : 
targetOS=linux-x86_64

> Task :compileTestJava 
warning: [options] bootstrap class path not set in conjunction with -source 1.7
<==========---> 81% EXECUTING [2m 41s]
> :test > 99 tests completed
> :test > Executing test org.audiveris.omr.util.BrokenLineTest

------------------------------------------------------------
Gradle 3.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.10.3 compiled on July 19 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.15.0-30-generic amd64

elacusta@elacusta-HP-Pavilion-dm1-Notebook-PC:~$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by elacusta** [comment]
Maxim,
Linux Mint do not allow to upgrade gradle above 3.4.1. I've tried manually
but there is an incompatibility with some library.
Using java java version "1.8.0_181"
I have tesseract installed (ver 4.00, with eng and por languages)
I've set the variable TESSATA_PREFIX to the correct path, but I still get
the error bellow.
Should I copy the tessaract data to some other folder?
Many thanks,
Eduardo

elacusta@elacusta-HP-Pavilion-dm1-Notebook-PC:~/audiveris$ export
TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/
elacusta@elacusta-HP-Pavilion-dm1-Notebook-PC:~/audiveris$ sudo ./gradlew
clean run

> Configure project :
targetOS=linux-x86_64

> Task :compileJava
warning: [options] bootstrap class path not set in conjunction with -source
1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :run FAILED
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.audiveris.omr.Main.<clinit>(Main.java:64)
        at Audiveris.main(Audiveris.java:49)
Caused by: org.audiveris.omr.WellKnowns$InstallationException: Tesseract
data could not be found. Try setting the TESSDATA_PREFIX environment
variable to the parent folder of "tessdata".
        at
org.audiveris.omr.WellKnowns.scanOcrLocations(WellKnowns.java:532)
        at org.audiveris.omr.WellKnowns.getOcrFolder(WellKnowns.java:484)
        at org.audiveris.omr.WellKnowns.<clinit>(WellKnowns.java:137)
        ... 2 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/opt/java/jdk1.8.0_181/bin/java'' finished with
non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
6 actionable tasks: 6 executed
elacusta@elacusta-HP-Pavilion-dm1-Notebook-PC:~/audiveris$


2018-08-17 5:34 GMT-03:00 Maxim Poliakovski <notifications@github.com>:

**Comment by maximumspatium** [comment]
> Linux Mint do not allow to upgrade gradle above 3.4.1. I've tried manually
> but there is an incompatibility with some library.

You shouldn't update anything manually. Just run the Gradle wrapper script using

`./gradlew`

instead of

`gradle`.

Easy, isn't?

Regarding the TESSDATA_PREFIX, you need to pay attention to two things:

1. It should be set correctly to the PARENT directory of tessdata. If, for example, Tesseract data is located in `/usr/share/tesseract-ocr/tessdata` you'll need to set TESSDATA_PREFIX to point to `/usr/share/tesseract-ocr` using `export TESSDATA_PREFIX="/usr/share/tesseract-ocr/"` command.

2. Please ensure that TESSDATA_PREFIX is permanent. Close your current terminal, open a new terminal window and issue `echo $TESSDATA_PREFIX` command. It should print out the correct path. If it doesn't, you'll need to adjust your bash profile accordingly.

IIRC, Linux Mint is a Debian/Ubuntu derivative, isn't? I don't remember the need to set any environment variable at all. Did you try to install Tesseract data files using the built-in package manager?

`sudo apt-get install tesseract-ocr-eng tesseract-oct-por`

It should work out-of-box this way...

**Comment by maximumspatium** [comment]
Moreover, I noticed that you're trying to install Audiveris **as root** (using `sudo`). I hope there is a special reason for that. Otherwise, you shouldn't install user-level Java software as root...

**Comment by hbitteur** [comment]
Audiveris does not yet support Tesseract 4.
IIRC 3.04 is Ok

**Comment by hbitteur** [comment]
Update: Tesseract 3.5.1
