### ISSUE TITLE
Error loading pdf

### ISSUE THREAD

**Issue by bastik** [Audiveris/audiveris#20]
Hi,
when opening a .pdf, I get the following error:
```
INFO  []                      Main 338  | Environment:
- Audiveris:    5.0.0:04e0239
- OS:           Linux 4.2.0-42-generic
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []             AliasPatterns 121  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []               Nd4jBackend 194  | Loaded [CpuBackend] backend
INFO  []           NativeOpsHolder 38   | Number of threads used for NativeOps: 4
INFO  []        AbstractClassifier 323  | Classifier data loaded from default file:///home/user/source/audiveris/res/basic-classifier.zip
INFO  [Dvorak-B17-v2]                 BasicBook 356  | 22 sheets in /home/user/Documents/cur/Dvorak-B17-v2.pdf
WARN  [Dvorak-B17-v2#1]                 BasicStub 836  | Error in LOAD java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.audiveris.omr.sheet.BasicStub.doOneStep(BasicStub.java:819)
	at org.audiveris.omr.sheet.BasicStub.reachStep(BasicStub.java:558)
	at org.audiveris.omr.sheet.ui.StubsController.checkStubStatus(StubsController.java:816)
	at org.audiveris.omr.sheet.ui.StubsController.access$200(StubsController.java:91)
	at org.audiveris.omr.sheet.ui.StubsController$3.call(StubsController.java:508)
	at org.audiveris.omr.sheet.ui.StubsController$3.call(StubsController.java:499)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError: null
	at de.intarsys.pdf.platform.cwt.font.freetype.FreetypeFontFactory.getLibrary(Unknown Source)
	at de.intarsys.pdf.platform.cwt.font.freetype.FreetypeFontFactory.createPlatformFont(Unknown Source)
	at de.intarsys.pdf.platform.cwt.rendering.CSPlatformDevice.textSetFont(Unknown Source)
	at de.intarsys.pdf.content.CSDeviceBasedInterpreter.render_Tf(Unknown Source)
	at de.intarsys.pdf.content.CSInterpreter.process(Unknown Source)
	at de.intarsys.pdf.content.CSInterpreter.process(Unknown Source)
	at de.intarsys.pdf.content.CSDeviceBasedInterpreter.process(Unknown Source)
	at org.audiveris.omr.image.ImageLoading$JPodLoader.getImage(ImageLoading.java:462)
	at org.audiveris.omr.sheet.BasicBook.loadSheetImage(BasicBook.java:977)
	at org.audiveris.omr.step.LoadStep.doit(LoadStep.java:71)
	at org.audiveris.omr.step.Step.doit(Step.java:168)
	at org.audiveris.omr.sheet.BasicStub$4.call(BasicStu809)va:
	at org.audiveris.omr.sheet.BasicStub$4.call(BasicStub.java:797)
	... 4 common frames omitted
Caused by: java.lang.NullPointerException: no native interface available
	at de.intarsys.nativec.api.NativeInterface.set(Unknown Source)
	at de.intarsys.nativec.api.NativeInterface.get(Unknown Source)
	at de.intarsys.cwt.freetype.nativec._FTNI.init(Unknown Source)
	at de.intarsys.cwt.freetype.nativec._FTNI.<init>(Unknown Source)
	at de.intarsys.cwt.freetype.Freetype.<clinit>(Unknown Source)
	... 17 common frames omitted
INFO  [Dvorak-B17-v2#1]                 BasicStub 841  | Cause java.lang.ExceptionInInitializerError
INFO  [Dvorak-B17-v2#1]                 BasicStub 565  | StepException detected in [LOAD, BINARY]
```

Loading and converting a .jpg score works fine, though. I'm quite pleased with the results so far.

**Comment by maximumspatium** [comment]
It looks like you are missing [Freetype](https://www.freetype.org) native library. Please install it using your system package manager.

**Comment by bastik** [comment]
The packages `libfreetype6` and `libfreetype6-dev` are installed.
```
$ file /usr/lib/x86_64-linux-gnu/libfreetype.so.6
/usr/lib/x86_64-linux-gnu/libfreetype.so.6: symbolic link to libfreetype.so.6.11.1
```

**Comment by maximumspatium** [comment]
Hmm, for the moment being, I have no idea why this exception is thrown. Could you share your pdf with me (over Dropbox, whatsoever) so I could give it try?

**Comment by bastik** [comment]
For example `audiveris/data/examples/Dichterliebe01.pdf` has the same error (any pdf I've tried).

**Comment by maximumspatium** [comment]
Well, it looks like [JNA](https://github.com/java-native-access/jna) which is called by Intarsys jPod Renderer can't load the freetype library. You need to ensure that libfreetype is available in a location JNA expects to find it. Try to set `LD_LIBRARY_PATH` appropriately before launching Audiveris.
Importing `Dicherliebe01.pdf` works flawlessly in my Ubuntu.

**Comment by bastik** [comment]
That didn't help. From the `strace`, it seems to look for a file `de/intarsys/cwt/freetype/nativec/default/freetype.zip` (unsuccessfully), there is no reference to `libfreetype.so` in the log.

**Comment by maximumspatium** [comment]
This is weird. `freetype.zip` should be used on Windows (sic!) only. It sounds like a bug in jPod Renderer, not Audiveris. I'll look into the source code of [isFreetype](https://wiki.intarsys.de/display/Opensource/isFreeType) tonight. Would you quickly post the exact metrics of your system (OS, CPU etc.)? Thanks.

**Comment by bastik** [comment]
Okay, problem was outdated Java version (8u91-b14, last version packaged on Ubuntu 15.10), it works with Java 8u131-b11. (sorry for the noise)

Btw., are you aware the recognition of the initial part, clef (in particular C-clef), meter and key signature, is a bit fragile at times? I'm not so familiar with the Audiveris interface and find this hard to correct in MuseScore later on. Are you at stage where you are interested in examples with (seemingly) blatant misses in the recognition?

**Comment by maximumspatium** [comment]
I'm glad you solved the issue!

> Btw., are you aware the recognition of the initial part, clef (in particular C-clef), meter and key signature, is a bit fragile at times? Are you at stage where you are interested in examples with (seemingly) blatant misses in the recognition?

It depends on the quality of the input scores. We're currently working on a toolset for building a ground-truth database of musical scores that will be later used for improving Audiveris recognition, see [here for further details.](https://github.com/Audiveris/omr-dataset-tools) You are welcome to contribute to this database.

I'll close this issue because the original problem is solved. Feel free to open another issue to share your samples.
