### ISSUE TITLE
Print option fails with exception

### ISSUE THREAD

**Issue by VanKurt** [Audiveris/audiveris#200]
I have a .png image that I would like to convert to a .pdf.
To do so I use the following command line:

> audiveris -batch -export -force -save -print -output "C:\Users\Vmwareuser\Desktop\outputs" "C:\Users\Vmwareuser\Desktop\inputs\tst.png"

This generates a perfect MusicXML file (yay!), but only an empty (0 byte) PDF. In the log I can see the following exception:

> 2018-08-27 03:32:05,295 INFO [tst]            BasicBook.java:498  | 1 sheet in C:\Users\Vmwareuser\Desktop\inputs\tst.png
> 2018-08-27 03:32:05,701 INFO []            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:05,701 INFO []            BasicBook.java:1462 | Book stored as C:\Users\Vmwareuser\Desktop\outputs\tst\tst.omr
> 2018-08-27 03:32:05,763 WARN []            BasicBook.java:1086 | Cannot write PDF to C:\Users\Vmwareuser\Desktop\outputs\tst\tst.pdf
> java.lang.NullPointerException: null
> 	at org.audiveris.omr.sheet.BasicSheet.getWidth(BasicSheet.java:910)
> 	at org.audiveris.omr.score.ui.BookPdfOutput.write(BookPdfOutput.java:98)
> 	at org.audiveris.omr.sheet.BasicBook.print(BasicBook.java:1083)
> 	at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:785)
> 	at org.audiveris.omr.CLI$CliTask.call(CLI.java:350)
> 	at org.audiveris.omr.Main.runBatchTasks(Main.java:316)
> 	at org.audiveris.omr.Main.main(Main.java:155)
> 	at Audiveris.main(Audiveris.java:49)
> 2018-08-27 03:32:05,763 INFO []            BasicBook.java:1113 | Book reaching PAGE on sheets:[#1]
> 2018-08-27 03:32:05,763 INFO [tst]       StepMonitoring.java:96   | LOAD
> 2018-08-27 03:32:05,935 INFO [tst]            BasicBook.java:1028 | Loaded image 1 1816x1182 from C:\Users\Vmwareuser\Desktop\inputs\tst.png
> 2018-08-27 03:32:05,935 INFO [tst]            ImageUtil.java:83   | Converting max RGB to gray ...
> 2018-08-27 03:32:06,154 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:07,185 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:07,218 INFO [tst]       StepMonitoring.java:96   | BINARY
> 2018-08-27 03:32:07,904 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:08,138 INFO [tst]              Picture.java:797  | Stored /sheet#1/BINARY.xml
> 2018-08-27 03:32:08,138 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:08,154 INFO [tst]       StepMonitoring.java:96   | SCALE
> 2018-08-27 03:32:08,482 INFO [tst]         ScaleBuilder.java:536  | Second combo peak too different (126,126,127), ignored
> 2018-08-27 03:32:08,482 INFO [tst]            ScaleStep.java:87   | Scale{line(2,2,3) interline(15,16,16) beam(9)}
> 2018-08-27 03:32:08,498 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:08,498 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:08,576 INFO [tst]       StepMonitoring.java:96   | GRID
> 2018-08-27 03:32:10,045 INFO [tst]       LinesRetriever.java:444  | Global slope: 0.00000
> 2018-08-27 03:32:10,123 INFO [tst]    ClustersRetriever.java:242  | Retrieved line clusters: 4 of size: 5 with interline: (15,16,16)
> 2018-08-27 03:32:10,326 INFO [tst]            PeakGraph.java:181  | Systems: #1[1, 2] #2[3, 4]
> 2018-08-27 03:32:10,873 INFO [tst]        SystemManager.java:745  | 1 part along 2 systems
> 2018-08-27 03:32:10,873 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:11,061 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:11,077 INFO [tst]       StepMonitoring.java:96   | HEADERS
> 2018-08-27 03:32:11,857 INFO [tst]      BasicClassifier.java:391  | Classifier loaded XML norms.
> 2018-08-27 03:32:11,889 INFO [tst]   AbstractClassifier.java:355  | Classifier data loaded from default uri jar:file:/C:/Program%20Files%20(x86)/Audiveris/lib/audiveris.jar!/res/basic-classifier.zip
> 2018-08-27 03:32:14,060 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:14,216 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:14,248 INFO [tst]       StepMonitoring.java:96   | STEM_SEEDS
> 2018-08-27 03:32:14,311 INFO [tst]        StemSeedsStep.java:92   | stem(2 max:4)
> 2018-08-27 03:32:14,452 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:14,592 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:14,654 INFO [tst]       StepMonitoring.java:96   | BEAMS
> 2018-08-27 03:32:17,389 INFO [tst]       BlackHeadSizer.java:99   | Spots black-head retrieval diameter: 14.4
> 2018-08-27 03:32:17,498 INFO [tst]       BlackHeadSizer.java:251  | Core black head count: 30 blackHead(width:19.1~0.3 height:16.9~0.9)
> 2018-08-27 03:32:17,514 INFO [tst]       BlackHeadSizer.java:256  | MusicFont{name:MusicalSymbols pointSize:64}
> 2018-08-27 03:32:17,826 INFO [tst]            BeamsStep.java:89   | BeamDistance{count:2 mean:0.25 stdDev:0.35}
> 2018-08-27 03:32:17,842 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:17,889 INFO [tst]              Picture.java:797  | Stored /sheet#1/HEAD_SPOTS.xml
> 2018-08-27 03:32:18,091 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:18,108 INFO [tst]       StepMonitoring.java:96   | LEDGERS
> 2018-08-27 03:32:18,607 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:18,795 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:18,826 INFO [tst]       StepMonitoring.java:96   | HEADS
> 2018-08-27 03:32:20,842 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:21,092 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:21,123 INFO [tst]       StepMonitoring.java:96   | STEMS
> 2018-08-27 03:32:21,748 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:22,295 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:22,326 INFO [tst]       StepMonitoring.java:96   | REDUCTION
> 2018-08-27 03:32:22,498 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:22,904 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:22,951 INFO [tst]       StepMonitoring.java:96   | CUE_BEAMS
> 2018-08-27 03:32:22,967 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:23,138 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:23,170 INFO [tst]       StepMonitoring.java:96   | TEXTS
> 2018-08-27 03:32:28,045 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:28,263 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:28,326 INFO [tst]       StepMonitoring.java:96   | MEASURES
> 2018-08-27 03:32:28,357 INFO [tst]                 Page.java:260  | 8 raw measures: [5 in system#1, 3 in system#2]
> 2018-08-27 03:32:28,373 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:28,607 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:28,623 INFO [tst]       StepMonitoring.java:96   | CHORDS
> 2018-08-27 03:32:28,716 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:28,935 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:28,951 INFO [tst]       StepMonitoring.java:96   | CURVES
> 2018-08-27 03:32:30,591 INFO [tst]         SlursBuilder.java:157  | Slurs: 5
> 2018-08-27 03:32:30,607 INFO [tst]      SegmentsBuilder.java:114  | Segments: 4
> 2018-08-27 03:32:30,623 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:30,888 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:30,935 INFO [tst]       StepMonitoring.java:96   | SYMBOLS
> 2018-08-27 03:32:31,310 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:31,591 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:31,607 INFO [tst]       StepMonitoring.java:96   | LINKS
> 2018-08-27 03:32:31,670 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:32,107 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:32,232 INFO [tst]       StepMonitoring.java:96   | RHYTHMS
> 2018-08-27 03:32:32,841 INFO [tst]           PageRhythm.java:380  | Range{1-8 ts:4/4 dur:1} guess:1
> 2018-08-27 03:32:32,920 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:33,216 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:33,248 INFO [tst]       StepMonitoring.java:96   | PAGE
> 2018-08-27 03:32:33,279 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:33,827 INFO [tst]           BasicSheet.java:1041 | Stored /sheet#1/sheet#1.xml
> 2018-08-27 03:32:33,842 INFO [tst]            BasicStub.java:758  | Sheet{tst} disposed
> 2018-08-27 03:32:35,217 INFO [tst]            BasicStub.java:484  | Loaded /sheet#1/sheet#1.xml
> 2018-08-27 03:32:35,232 INFO [tst]            BasicBook.java:1234 | Scores built: 1
> 2018-08-27 03:32:38,591 INFO [tst]        ScoreExporter.java:93   | Score tst exported to C:\Users\Vmwareuser\Desktop\outputs\tst\tst.mxl
> 2018-08-27 03:32:38,763 INFO [tst]            BasicBook.java:1502 | Stored /book.xml
> 2018-08-27 03:32:38,763 INFO [tst]            BasicBook.java:1462 | Book stored as C:\Users\Vmwareuser\Desktop\outputs\tst\tst.omr

**Comment by maximumspatium** [comment]
@VanKurt Can you share your PNG input with us?

**Comment by VanKurt** [comment]
<img width="908" alt="test" src="https://user-images.githubusercontent.com/5222025/44971018-5b610a00-af54-11e8-8380-88337a275d69.png">
Sure thing. Here's the file.
