### ISSUE TITLE
Can't start on Windows

### ISSUE THREAD

**Issue by eejake52** [Audiveris/audiveris#204]
I downloaded Windows installer V5.1rc02 from the Releases tab and installed on Windows 10 (64 bit). When I try to run Audiveris.bat, I get the following error:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:613)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.lept.<clinit>(lept.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.load(Loader.java:585)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.tesseract$TessBaseAPI.<clinit>(tesseract.java:3648)
        at org.audiveris.omr.text.tesseract.TesseractOCR.identify(TesseractOCR.java:151)
        at org.audiveris.omr.Main.showEnvironment(Main.java:347)
        at org.audiveris.omr.Main.main(Main.java:124)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.UnsatisfiedLinkError: no liblept in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:604)
        ... 11 more
Press any key to continue . . .`

So, am I missing a dependency? or is it something else?

Thanks,
Jake

**Comment by hbitteur** [comment]
@eejake52 
Beware, the Windows installer you tried is just an early version, not officially released yet.
It is important to understand what failed in your case.

Could you tell us:
- Which Java version you are using (7 or preferably 8 are OK). I'm not sure at all that Java 9 would be OK.
- In the Audiveris installation folder (generally located at C:\Program Files (x86)\Audiveris), check in the lib sub-folder that there is a leptonica-1.73-1.3-windows-x86_64.jar (it is this archive which contains a jnilept.dll, the library you could not find)

**Comment by eejake52** [comment]
Hervé,
I have Java Version 1.8.0_181.
Yes I see leptonica-1.73-1.3-windows-x86_64.jar in the location you suggested.

I am happy to provide testing for this rc version, but in parallel with that, what is the latest stable/tested version known to work on Windows 10?






________________________________

**Comment by hbitteur** [comment]
We are just about to release 5.1 (a couple of weeks perhaps). It just happened that we decided to add an installer very recently...

But you can already use the "development" branch which will end up as 5.1 release. It is significantly better than 5.0 and quite stable now.
But you have to forget about installer for a while (until we fix your installation problem) and download and build on your own.
Not a big deal, eveything is explained in the README.md: you need git to clone the project and to switch to development branch (by means of "git checkout development") and then build the project by means of gradlew build and run.

**Comment by eejake52** [comment]
I found a temporary solution. I installed the JDK (previously I just had the JRE), removed Audiveris, then reinstalled Audiveris. So, something in the JDK is a prerequisite, or possibly the Audiveris installer needs to point to the JRE (as opposed to the JDK). In any event, the program starts, so now I just have to learn how to use it.

**Comment by hbitteur** [comment]
I still don't have a definitive answer, but I'm puzzled by the impact of JRE/JDK.
I'm positive, you don't need a JDK, just a JRE.

But perhaps, the JRE you had previously was a 32-bit JRE (which would explain the problem when trying to load 64-bit DLLs).
Then, you installed a JDK (perhaps a 64-bit this time, which would explain why it now works).

Fighting with the building of Windows Installers right now, I just encountered the same behavior as yours (i.e. not finding this jnilept lib) because I was trying to load the 32-bit leptonica-1.73-1.3-windows-x86.jar on a 64-bit JVM: just the opposite of your case, perhaps).
Hence my question.

**Comment by eejake52** [comment]
Herve,
I agree with your hypothesis. I do see both 32 and 64 bit versions of Java on my computer. Judging  by the dates on the file folders, the 64 bit JRE & JDK were installed after I had submitted my original post to you. Hope that helps.

**Comment by hbitteur** [comment]
Thanks Jake.
I'm glad to read that.
Finally, I can close the issue.
