### ISSUE TITLE
Hilarious build

### ISSUE THREAD

**Issue by sguillia** [Audiveris/audiveris#214]
Hi

I launched `./gradlew build` and went away for a coffee.

I came back one hour later and the file `audiveris/build/test-results/test/binary/output.bin` had a size of 27Go !!

It is filled with one java backtrace that never ends (I killed the build with Ctrl+C).

<details> 
  <summary>Click to show part of backtrace</summary>

```
^A^B^A^RtestMultipleCalls
^A^D^C  addPoint
^A^D^C$before: [(1,5) (10,5) (10,1) (1,1)]
^A^D^C*after : [(1,5) (10,5) (10,1) (1,1) (2,3)]
^A^D^E^NaddPointEmpty
^A^D^E^Kbefore: []
^A^D^E^Pafter : [(2,3)]
^A^D^F#findPoint java.awt.Point[x=10,y=1]
^A^D^F$before: [(1,5) (10,5) (10,1) (1,1)]
^A^D^Fz16:16:21.136 [Test worker] WARN org.audiveris.omr.constant.ConstantSet - Error initializing map of ConstantSet BrokenLine
^A^D^F,java.lang.ExceptionInInitializerError: null
^A^D^FP at org.audiveris.omr.constant.ConstantManager.<init>(ConstantManager.java:143)
^A^D^FR at org.audiveris.omr.constant.ConstantManager.<clinit>(ConstantManager.java:133)
^A^D^FJ at org.audiveris.omr.constant.Constant.setUnitAndName(Constant.java:381)
^A^D^FI at org.audiveris.omr.constant.ConstantSet.initMap(ConstantSet.java:265)
^A^D^FH at org.audiveris.omr.constant.ConstantSet.getMap(ConstantSet.java:228)
^A^D^FL at org.audiveris.omr.constant.ConstantSet.initialize(ConstantSet.java:177)
^A^D^FP at org.audiveris.omr.constant.UnitManager.checkDirtySets(UnitManager.java:179)
^A^D^FL at org.audiveris.omr.constant.Constant.checkInitialized(Constant.java:446)
^A^D^FD at org.audiveris.omr.constant.Constant.getTuple(Constant.java:468)
^A^D^FJ at org.audiveris.omr.constant.Constant.getCachedValue(Constant.java:328)
^A^D^FD at org.audiveris.omr.constant.Constant.getValue(Constant.java:221)
^A^D^FM at org.audiveris.omr.util.BrokenLine.getStickyDistance(BrokenLine.java:146)
^A^D^FE at org.audiveris.omr.util.BrokenLine.findPoint(BrokenLine.java:175)
^A^D^FM at org.audiveris.omr.util.BrokenLineTest.findPoint(BrokenLineTest.java:108)
^A^D^F@ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
^A^D^FR at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
^A^D^FZ at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
^A^D^F5 at java.lang.reflect.Method.invoke(Method.java:498)
^A^D^FY at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
^A^D^FX at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
^A^D^FW at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
^A^D^FV at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
^A^D^FR at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
^A^D^FB at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
^A^D^FV at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
^A^D^FV at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
^A^D^F@ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
^A^D^FD at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
^A^D^FF at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
^A^D^FD at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
^A^D^FE at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
^A^D^F> at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
^A^D^Fu at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:116)
^A^D^Fo at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:59)
^A^D^Fo at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
^A^D^F<8A>^A    at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
^A^D^Ft at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
^A^D^F@ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
^A^D^FR at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
^A^D^FZ at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
^A^D^F5 at java.lang.reflect.Method.invoke(Method.java:498)
^A^D^FY at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
^A^D^FY at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
^A^D^Fi at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
^A^D^Fx at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
^A^D^F; at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
^A^D^Fb at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
^A^D^F@ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
^A^D^FR at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
^A^D^FZ at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
^A^D^F5 at java.lang.reflect.Method.invoke(Method.java:498)
^A^D^FY at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
^A^D^FY at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
^A^D^F<91>^A    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
^A^D^F<91>^A    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
^A^D^FX at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
^A^D^Fk at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
^A^D^FZ at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
^A^D^FT at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
^A^D^FT at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
^A^D^Fj at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
^A^D^F* at java.lang.Thread.run(Thread.java:748)
^A^D^F<BB>^ACaused by: org.audiveris.omr.WellKnowns$InstallationException: Tesseract data could not be found. Try setting the TESSDATA_PREFIX environment variable to the parent folder of "tessdata".
^A^D^FG at org.audiveris.omr.WellKnowns.scanOcrLocations(WellKnowns.java:532)
^A^D^FC at org.audiveris.omr.WellKnowns.getOcrFolder(WellKnowns.java:484)
^A^D^F? at org.audiveris.omr.WellKnowns.<clinit>(WellKnowns.java:137)
^A^D^F^^        ... 62 common frames omitted
^A^D^Fz16:16:21.171 [Test worker] WARN org.audiveris.omr.constant.ConstantSet - Error initializing map of ConstantSet BrokenLine
^A^D^Ffjava.lang.NoClassDefFoundError: Could not initialize class org.audiveris.omr.constant.ConstantManager
^A^D^FJ at org.audiveris.omr.constant.Constant.setUnitAndName(Constant.java:381)
^A^D^FI at org.audiveris.omr.constant.ConstantSet.initMap(ConstantSet.java:265)
^A^D^FH at org.audiveris.omr.constant.ConstantSet.getMap(ConstantSet.java:228)
^A^D^FL at org.audiveris.omr.constant.ConstantSet.initialize(ConstantSet.java:177)
^A^D^FP at org.audiveris.omr.constant.UnitManager.checkDirtySets(UnitManager.java:179)
^A^D^FL at org.audiveris.omr.constant.Constant.checkInitialized(Constant.java:446)
^A^D^FD at org.audiveris.omr.constant.Constant.getTuple(Constant.java:468)
^A^D^FJ at org.audiveris.omr.constant.Constant.getCachedValue(Constant.java:328)
^A^D^FD at org.audiveris.omr.constant.Constant.getValue(Constant.java:221)
^A^D^FM at org.audiveris.omr.util.BrokenLine.getStickyDistance(BrokenLine.java:146)
^A^D^FE at org.audiveris.omr.util.BrokenLine.findPoint(BrokenLine.java:175)
^A^D^FM at org.audiveris.omr.util.BrokenLineTest.findPoint(BrokenLineTest.java:108)
^A^D^F@ at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

</details>
<br>
Is this a problem on my side?

**Comment by hbitteur** [comment]
Have look at issue #205 which may be your case.

If so, either make sure that Tesseract data is available,
or switch to "development" branch (where the issue is fixed) and launch a clean build.

 Or wait a couple of days, because release 5.1 is to be published this week.
