### ISSUE TITLE
"FT_Get_First_Char" error

### ISSUE THREAD

**Issue by PlauditsForAudits** [Audiveris/audiveris#255]
I've installed the 64-bit JRE 1.8.0u202, Tesseract 3.04.01, and the 64-bit Audiveris Windows binary. The GUI opens OK, but when I input a PDF, I'm told that FT_Get_First_Char is missing. Here's the command prompt output, truncating the stack trace:

```
INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.0:4687c3527
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: []
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                   MainGui 499  | Audiveris version 5.1.0
INFO  []                   MainGui 500  |
LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No C:\Users\me\AppData\Roaming\AudiverisLtd\audiveris\config\logback.xml, skipped.
LogUtil. Configuration found jar:file:/C:/Program%20Files/Audiveris/lib/audiveris.jar!/res/logback.xml
LogUtil. Logging to C:\Users\me\AppData\Roaming\AudiverisLtd\audiveris\log\20190223T060634.log

INFO  []            PluginsManager 235  | No C:\Users\taxsh\AppData\Roaming\AudiverisLtd\audiveris\config\plugins.xml file found
INFO  []           BasicClassifier 362  | Classifier loaded XML norms.
INFO  []        AbstractClassifier 348  | Classifier data loaded from default uri jar:file:/C:/Program%20Files/Audiveris/lib/audiveris.jar!/res/basic-classifier.zip
INFO  [BWV_775_sheet_music]                      Book 473  | 2 sheets in C:\docs\BWV_775_sheet_music.pdf
WARN  [BWV_775_sheet_music#1]                 SheetStub 845  | Error in performing [LOAD, BINARY] java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: Error looking up function 'FT_Get_First_Char': The specified procedure could not be found.

java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: Error looking up function 'FT_Get_First_Char': The specified procedure could not be found.

        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1111)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:832)
 [...]
```

```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

Thoughts? I've searched and stared at the doc, but I'm not seeing my mistake.

**Comment by maximumspatium** [comment]
It looks like you have two JREs installed: OpenJDK 1.8.0_151 und Oracle 1.8.0_202.

If I'm reading the above mentioned log correctly, Audiveris picked up the old JRE:
`Java VM:      OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)`

Please go ahead and check up your JRE installation. I'd recommend to keep the recent version and remove the obsolete one.

**Comment by maximumspatium** [comment]
@PlauditsForAudits Any update regarding your issue?

**Comment by maximumspatium** [comment]
Closed due to inactivity.
