### ISSUE TITLE
Timeout steps TEXTS: skip step to continue

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#261]
in seldom cases transcription is stopped in step TEXTS due to complex texts in the score.
Unfortunately it is not possible to continue without text recognition. 
It would make sense to allow continuing without text recognition - in many cases this is better than having nothing...

**Comment by Winand** [comment]
See [Gravity falls.pdf](https://github.com/Audiveris/audiveris/files/7790311/Gravity.falls.3.pdf) ([source](https://disk.yandex.ru/d/5zPbngvwWep5Yg))

```
WARN  [Gravity falls (3)#1]               TextBuilder 650  | Error in guessRole for TextLine{ "  10 10 10 10" bounds[-10,908,1437,1804] conf:0.95 base[796,924]-[1427,932]} java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sheet.Staff.getAbscissa(org.audiveris.omr.util.HorizontalSide)" because "staff" is null
java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sheet.Staff.getAbscissa(org.audiveris.omr.util.HorizontalSide)" because "staff" is null
        at org.audiveris.omr.text.TextRole.guessRole(TextRole.java:159)
        at org.audiveris.omr.text.TextBuilder.guessRole(TextBuilder.java:647)
        at org.audiveris.omr.text.TextBuilder.guessLongRoles(TextBuilder.java:627)
        at org.audiveris.omr.text.TextBuilder.processSystem(TextBuilder.java:352)
        at org.audiveris.omr.text.TextsStep.doSystem(TextsStep.java:91)
        at org.audiveris.omr.text.TextsStep.doSystem(TextsStep.java:50)
        at org.audiveris.omr.step.AbstractSystemStep.lambda$doitPerSystem$0(AbstractSystemStep.java:191)
        at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:211)
        at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:104)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.SheetStub.lambda$doOneStep$3(SheetStub.java:1248)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
        ...
```

**Comment by Winand** [comment]
Also to just skip TEXTS step one can change `useOCR` in settings to `false`

**Comment by hbitteur** [comment]
Closing the issue
