### ISSUE TITLE
Incomplete musicXML files when using the API

### ISSUE THREAD

**Issue by deepio** [Audiveris/audiveris#272]
Using audiveris with the flags `batch` `export` `save` `output`, creates two zipped documents *.omr and *.mxl. Only the *.mxl extracts an xml document with MusicXML attributes. However, this document contains nothing but margin data. Am I missing any additional flags?

**Comment by maximumspatium** [comment]
It's difficult to tell without seeing the precise command/input. Can you post them here?

Did you try to start Audiveris in the GUI mode and to transcribe your input there? Does it work as expected?

**Comment by deepio** [comment]
You can try it yourself in my docker container: https://github.com/deepio/Andean-Bears/tree/master/audiveris

Using: `docker-compose up`, it will automatically run on all the images inside the `to_scan` directory.
Unzip the `*.mxl` and see for yourself.

**Comment by deepio** [comment]
```bash
Attaching to andean-bears_audiveris_omr_1
[36maudiveris_omr_1  |[0m INFO  []                      Main 334  | Environment:
[36maudiveris_omr_1  |[0m - Audiveris:    5.1.0:6780b1f91
[36maudiveris_omr_1  |[0m - OS:           Linux 4.9.125-linuxkit
[36maudiveris_omr_1  |[0m - Architecture: amd64
[36maudiveris_omr_1  |[0m - Java VM:      OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
[36maudiveris_omr_1  |[0m - OCR Engine:   Tesseract OCR, version 3.04.01
[36maudiveris_omr_1  |[0m INFO  []                       CLI 217  | CLI args: [-batch, -export, -save, -output, /OMR/finished/, /OMR/to_scan/Adagio-page1-075.tiff, /OMR/to_scan/Adagio-page1-100.tiff, /OMR/to_scan/Adagio-page1-150.tiff, /OMR/to_scan/Adagio-page1-200.tiff]
[36maudiveris_omr_1  |[0m INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
[36maudiveris_omr_1  |[0m INFO  []                      Main 147  | Running in batch mode
[36maudiveris_omr_1  |[0m INFO  []                      Main 251  | Submitting 4 task(s) in sequence:
[36maudiveris_omr_1  |[0m     Input "/OMR/to_scan/Adagio-page1-075.tiff"
[36maudiveris_omr_1  |[0m     Input "/OMR/to_scan/Adagio-page1-100.tiff"
[36maudiveris_omr_1  |[0m     Input "/OMR/to_scan/Adagio-page1-150.tiff"
[36maudiveris_omr_1  |[0m     Input "/OMR/to_scan/Adagio-page1-200.tiff"
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                      Book 473  | 1 sheet in /OMR/to_scan/Adagio-page1-075.tiff
[36maudiveris_omr_1  |[0m INFO  []                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  []                      Book 1613 | Book stored as /OMR/finished/Adagio-page1-075/Adagio-page1-075.omr
[36maudiveris_omr_1  |[0m INFO  []                      Book 1327 | Book reaching PAGE on sheets:[#1]
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]            StepMonitoring 93   | LOAD
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                      Book 1226 | Loaded image 1 549x817 from /OMR/to_scan/Adagio-page1-075.tiff
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                 ImageUtil 81   | Converting max RGB to gray ...
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]            StepMonitoring 93   | BINARY
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                   Picture 784  | Stored /sheet#1/BINARY.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]            StepMonitoring 93   | SCALE
[36maudiveris_omr_1  |[0m WARN  [Adagio-page1-075]                 SheetStub 310  | Adagio-page1-075 With an interline value of 4 pixels, either this sheet contains no staves, or the picture resolution is too low (try 300 DPI).
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                 SheetStub 683  | Sheet Adagio-page1-075 flagged as invalid.
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                 SheetStub 843  | StepException cause detected in [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE]
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-075]                      Book 1613 | Book stored as /OMR/finished/Adagio-page1-075/Adagio-page1-075.omr
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                      Book 473  | 1 sheet in /OMR/to_scan/Adagio-page1-100.tiff
[36maudiveris_omr_1  |[0m INFO  []                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  []                      Book 1613 | Book stored as /OMR/finished/Adagio-page1-100/Adagio-page1-100.omr
[36maudiveris_omr_1  |[0m INFO  []                      Book 1327 | Book reaching PAGE on sheets:[#1]
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]            StepMonitoring 93   | LOAD
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                      Book 1226 | Loaded image 1 731x1089 from /OMR/to_scan/Adagio-page1-100.tiff
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                 ImageUtil 81   | Converting max RGB to gray ...
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]            StepMonitoring 93   | BINARY
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                   Picture 784  | Stored /sheet#1/BINARY.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]            StepMonitoring 93   | SCALE
[36maudiveris_omr_1  |[0m WARN  [Adagio-page1-100]                 SheetStub 310  | Adagio-page1-100 With an interline value of 6 pixels, either this sheet contains no staves, or the picture resolution is too low (try 300 DPI).
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                 SheetStub 683  | Sheet Adagio-page1-100 flagged as invalid.
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                 SheetStub 843  | StepException cause detected in [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE]
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-100]                      Book 1613 | Book stored as /OMR/finished/Adagio-page1-100/Adagio-page1-100.omr
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                      Book 473  | 1 sheet in /OMR/to_scan/Adagio-page1-150.tiff
[36maudiveris_omr_1  |[0m INFO  []                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  []                      Book 1613 | Book stored as /OMR/finished/Adagio-page1-150/Adagio-page1-150.omr
[36maudiveris_omr_1  |[0m INFO  []                      Book 1327 | Book reaching PAGE on sheets:[#1]
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]            StepMonitoring 93   | LOAD
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                      Book 1226 | Loaded image 1 1097x1633 from /OMR/to_scan/Adagio-page1-150.tiff
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                 ImageUtil 81   | Converting max RGB to gray ...
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]            StepMonitoring 93   | BINARY
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                   Picture 784  | Stored /sheet#1/BINARY.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]            StepMonitoring 93   | SCALE
[36maudiveris_omr_1  |[0m WARN  [Adagio-page1-150]                 SheetStub 310  | Adagio-page1-150 With an interline value of 8 pixels, either this sheet contains no staves, or the picture resolution is too low (try 300 DPI).
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                 SheetStub 683  | Sheet Adagio-page1-150 flagged as invalid.
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                 SheetStub 843  | StepException cause detected in [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE]
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-150]                      Book 1613 | Book stored as /OMR/finished/Adagio-page1-150/Adagio-page1-150.omr
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 473  | 1 sheet in /OMR/to_scan/Adagio-page1-200.tiff
[36maudiveris_omr_1  |[0m INFO  []                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  []                      Book 1613 | Book stored as /OMR/finished/Adagio-page1-200/Adagio-page1-200.omr
[36maudiveris_omr_1  |[0m INFO  []                      Book 1327 | Book reaching PAGE on sheets:[#1]
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | LOAD
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1226 | Loaded image 1 1463x2178 from /OMR/to_scan/Adagio-page1-200.tiff
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                 ImageUtil 81   | Converting max RGB to gray ...
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | BINARY
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                   Picture 784  | Stored /sheet#1/BINARY.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | SCALE
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]              ScaleBuilder 492  | Beam minHeight:4 maxHeight:10 quorum:1740
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                 ScaleStep 84   | Scale{line(2,3,4) interline(10,11,12) beam(8)}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | GRID
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            LinesRetriever 447  | Global slope: 0.00000
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]         ClustersRetriever 235  | Retrieved line clusters: 15 of size: 5 with interline: interline(10,11,12)
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                 PeakGraph 177  | Systems: #1[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] #2[12, 13, 14, 15]
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 901  | No brace partner at level:2 for Peak{238-258 F#2491 T#5 [BRACE]}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 901  | No brace partner at level:2 for Peak{244-259 F#2492 T#6 [BRACE]}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 901  | No brace partner at level:2 for Peak{161-181 F#2506 T#15 [BRACE]}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 1378 | System#1
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 1381 |    PartGroup{bracket number:1 barline:true staves:1-4}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 1381 |    PartGroup{bracket number:1 barline:true staves:5-6}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 1381 |    PartGroup{bracket number:1 barline:true staves:8-11}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 1381 |    PartGroup{brace number:2 barline:true staves:8-9}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 1378 | System#2
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 1381 |    PartGroup{bracket number:1 barline:true staves:12-15}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             BarsRetriever 1381 |    PartGroup{brace number:2 barline:true staves:12-13}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             SystemManager 648  | Indentation detected for system#1
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             SystemManager 731  | 11 parts along 2 systems
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | HEADERS
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]           BasicClassifier 362  | Classifier loaded XML norms.
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]        AbstractClassifier 348  | Classifier data loaded from default uri jar:file:/Audiveris/lib/audiveris.jar!/res/basic-classifier.zip
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | STEM_SEEDS
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             StemSeedsStep 93   | stem(3 max:5)
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | BEAMS
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            BlackHeadSizer 95   | Spots black-head retrieval diameter: 9.9
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            BlackHeadSizer 243  | Core black head count: 38 blackHead(width:15.2~0.4 height:13.5~0.6)
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            BlackHeadSizer 248  | MusicFont{name:MusicalSymbols pointSize:51}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                 BeamsStep 86   | BeamDistance{count:56 mean:4.91 stdDev:5.48}
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                   Picture 784  | Stored /sheet#1/HEAD_SPOTS.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | LEDGERS
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | HEADS
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | STEMS
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | REDUCTION
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | CUE_BEAMS
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]            StepMonitoring 93   | TEXTS
[36maudiveris_omr_1  |[0m Failed loading language 'deu'
[36maudiveris_omr_1  |[0m Failed loading language 'eng'
[36maudiveris_omr_1  |[0m Error opening data file /opt/tessdata/fra.traineddata
[36maudiveris_omr_1  |[0m Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
[36maudiveris_omr_1  |[0m Failed loading language 'fra'
[36maudiveris_omr_1  |[0m Tesseract couldn't load any languages!
[36maudiveris_omr_1  |[0m WARN  [Adagio-page1-200]            TesseractOrder 166  | Could not initialize Tesseract with lang deu+eng+fra
[36maudiveris_omr_1  |[0m WARN  [Adagio-page1-200]                 SheetStub 845  | Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
[36maudiveris_omr_1  |[0m java.util.concurrent.ExecutionException: java.lang.NullPointerException
[36maudiveris_omr_1  |[0m 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[36maudiveris_omr_1  |[0m 	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1111)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:832)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.sheet.Book.reachBookStep(Book.java:1393)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.sheet.Book.transcribe(Book.java:1718)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.sheet.Book.export(Book.java:591)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:447)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.CLI$CliTask.call(CLI.java:538)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.Main.runBatchTasks(Main.java:312)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.Main.main(Main.java:153)
[36maudiveris_omr_1  |[0m 	at Audiveris.main(Audiveris.java:49)
[36maudiveris_omr_1  |[0m Caused by: java.lang.NullPointerException: null
[36maudiveris_omr_1  |[0m 	at java.util.ArrayList.addAll(ArrayList.java:581)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:80)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:42)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:98)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.step.Step.doit(Step.java:184)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1101)
[36maudiveris_omr_1  |[0m 	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1089)
[36maudiveris_omr_1  |[0m 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[36maudiveris_omr_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[36maudiveris_omr_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[36maudiveris_omr_1  |[0m 	at java.lang.Thread.run(Thread.java:748)
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1451 | Scores built: 1
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]             ScoreExporter 88   | Score Adagio-page1-200 exported to /OMR/finished/Adagio-page1-200/Adagio-page1-200.mxl
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1660 | Stored /book.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
[36maudiveris_omr_1  |[0m INFO  [Adagio-page1-200]                      Book 1613 | Book stored as /OMR/finished/Adagio-page1-200/Adagio-page1-200.omr
[36mandean-bears_audiveris_omr_1 exited with code 0
[0m
```

**Comment by hbitteur** [comment]
Tesseract software is not installed in your environment. 
It is mandatory for Audiveris.

**Comment by deepio** [comment]
@hbitteur it is 
https://github.com/deepio/Andean-Bears/blob/dbbf5e0f8e70594f8480d840cf09fa7454965c7c/audiveris/Dockerfile#L10

But that was not the issue, I had a typo in the environment where tesseract attempts to find language data. 
https://github.com/deepio/Andean-Bears/blob/dbbf5e0f8e70594f8480d840cf09fa7454965c7c/audiveris/Dockerfile#L2 
should have been `/opt/tessdata` 

So every time language data is not at least found, it will fail to create the .mxl file it seems. Meaning I must install all the languages from tesseract in order to make this work.

**Comment by deepio** [comment]
I have successfully created a full MusicXML file with the solution above. Closing the issue.
