### ISSUE TITLE
Error in GridBuilder

### ISSUE THREAD

**Issue by karimkalimu** [Audiveris/audiveris#278]
Hello 
This image the only one from all the pdf file always giving me this error even when I tried to brightness it or apply guassianblur filter then apply unsharp mask on it, also tried to delete the title or delete all the upper part( system 1 ) and it didn't work ,  Am trying to figure out why and I tried much worse than this image quality and audiveris gave me at least measures and staff lines correctly .

I just want to know why some images audiveris giving such error , and if there are any preprocessing procedure I can do to the image other than brightness and guassianblur .

(base) karims-MacBook-Pro:distributions karim$ bash Audiveris/bin/Audiveris -batch -export -output musicXML  -- /Users/karim/Downloads/IMSLP565025before.jpg 
INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.0:6780b1f91
- OS:           Mac OS X 10.14.4
- Architecture: x86_64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: [-batch, -export, -output, musicXML, --, /Users/karim/Downloads/IMSLP565025before.jpg]
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                      Main 147  | Running in batch mode
INFO  []                      Main 251  | Submitting 1 task(s) in sequence:
    Input "/Users/karim/Downloads/IMSLP565025before.jpg"
INFO  [IMSLP565025before]                      Book 473  | 1 sheet in /Users/karim/Downloads/IMSLP565025before.jpg
INFO  []                      Book 1660 | Stored /book.xml
INFO  []                      Book 1613 | Book stored as musicXML/IMSLP565025before/IMSLP565025before.omr
INFO  []                      Book 1327 | Book reaching PAGE on sheets:[#1]
INFO  [IMSLP565025before]            StepMonitoring 93   | LOAD
INFO  [IMSLP565025before]                      Book 1226 | Loaded image 1 1965x2475 from /Users/karim/Downloads/IMSLP565025before.jpg
INFO  [IMSLP565025before]            StepMonitoring 93   | BINARY
INFO  [IMSLP565025before]            StepMonitoring 93   | SCALE
INFO  [IMSLP565025before]              ScaleBuilder 492  | Beam minHeight:4 maxHeight:10 quorum:3128
INFO  [IMSLP565025before]                 ScaleStep 84   | Scale{line(2,3,4) interline(10,11,12) beam(8)}
INFO  [IMSLP565025before]            StepMonitoring 93   | GRID
INFO  [IMSLP565025before]            LinesRetriever 447  | Global slope: 0.00029
INFO  [IMSLP565025before]         ClustersRetriever 235  | Retrieved line clusters: 20 of size: 5 with interline: interline(10,11,12)
WARN  [IMSLP565025before]               GridBuilder 144  | Error in GridBuilder: java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.jgrapht.graph.AbstractBaseGraph.getEdgeSource(AbstractBaseGraph.java:233)
	at org.audiveris.omr.sheet.grid.PeakGraph.checkConnection(PeakGraph.java:447)
	at org.audiveris.omr.sheet.grid.PeakGraph.findAlignmentsAndConnectionsOf(PeakGraph.java:726)
	at org.audiveris.omr.sheet.grid.PeakGraph.splitPeak(PeakGraph.java:1333)
	at org.audiveris.omr.sheet.grid.PeakGraph.splitMergedGroups(PeakGraph.java:1266)
	at org.audiveris.omr.sheet.grid.PeakGraph.buildSystems(PeakGraph.java:160)
	at org.audiveris.omr.sheet.grid.BarsRetriever.process(BarsRetriever.java:232)
	at org.audiveris.omr.sheet.grid.GridBuilder.buildInfo(GridBuilder.java:126)
	at org.audiveris.omr.sheet.grid.GridStep.doit(GridStep.java:92)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1101)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1089)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARN  [IMSLP565025before]                   Picture 891  | No system lines to build NO_STAFF buffer

![IMSLP565025before](https://user-images.githubusercontent.com/40322180/56950380-eb993280-6b67-11e9-9065-30ab4bfec67d.jpg)

And thank all of you very much all audiveris team for this great job .

**Comment by Bacchushlg** [comment]
I don't get the error that you describe.
But anyway, just try to resize the image (I tried 150%): you should get a rather acceptable transcription with this (the actual interline value is just at the lowest limit and not enough for a good recognition).
If you have scanned the image yourself, try a better resolution.

**Comment by karimkalimu** [comment]
Thank you for response 

Actually I tried to resize the image by several sizes and change the dpi several times too, but it's still giving me the same error .

> I don't get the error that you describe.
I will try it on another computer and see maybe the error caused from something else .

And the sheet it's from IMSlP http://conquest.imslp.info/files/imglnks/usimg/c/c1/IMSLP02041-BWV1048.pdf , but it's bad quality as you said, I'm trying to see what possible action I can do to improve the quality other than unsharpMask and adjust brightness .

**Comment by Bacchushlg** [comment]
I have looked at the source... The quality is really bad. The major problem is that the double beams are no more separated so that Audiveris has no chance to detect the mean beams width.

**Comment by karimkalimu** [comment]
Thanks again 

Just to recap some kind of things like double beams or interline if they were hard to detect I can't do much .

I was trying with another sheet music  and I found that sometime it detect the half note as barline
name in IMSLP :  Symphonie concertante No.3, Op.34b 
Violin 2 part
https://imslp.org/wiki/Symphonie_concertante_No.3,_Op.34b_(Alard,_Jean_Delphin)#IMSLP81570

**Comment by hbitteur** [comment]
Closing because of no activity.
