### ISSUE TITLE
Could not initialize Tesseract with lang deu+eng+fra

### ISSUE THREAD

**Issue by Kitami** [Audiveris/audiveris#297]
hello i was use macOS and installed tesseract 4.0.0 (by brew)
but audiveris can not recognize any character and write error log like that
and The biggest problem is exported empty mxl file.(i tried several pdf and jpg score)
exported pdf is looks good.

2019-07-12 21:19:47,753 WARN  [score]            TesseractOrder 166  | Could not initialize Tesseract with lang deu+eng+fra
2019-07-12 21:19:47,755 WARN  [score]                 SheetStub 845  | Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1111)
	at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:832)
	at org.audiveris.omr.sheet.Book.reachBookStep(Book.java:1393)
	at org.audiveris.omr.sheet.Book.transcribe(Book.java:1718)
	at org.audiveris.omr.sheet.Book.export(Book.java:591)
	at org.audiveris.omr.sheet.ui.BookActions$ExportBookTask.doInBackground(BookActions.java:1889)
	at org.audiveris.omr.sheet.ui.BookActions$ExportBookTask.doInBackground(BookActions.java:1862)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:80)
	at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:42)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:98)
	at org.audiveris.omr.step.Step.doit(Step.java:184)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1101)
	at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1089)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted

**Comment by maximumspatium** [comment]
Tesseract 4 isn't supported yet, see #273 why. This has been discussed numerous times before, for example [here](https://github.com/Audiveris/audiveris/issues/289#issuecomment-500760400).
Downgrade to Tesseract 3.x and everything will be ok.

**Comment by Kitami** [comment]
thanks, i use the tessdata 3.04.00 release (https://github.com/tesseract-ocr/tessdata) and it is work now 
I misunderstood it as ”langdata” so didn't get it for those discussion
