### ISSUE TITLE
"Cannot create folder" issue, newest windows version

### ISSUE THREAD

**Issue by ci7sta** [Audiveris/audiveris#304]
Hello,

I'm currently having issues when trying to export a transcribed file. When I attempt it, I receive this error:
WARN  []               BookManager 414  | Cannot create folder C:\Users\tehru\Documents\Audiveris\allegretto
java.nio.file.NoSuchFileException: C:\Users\tehru\Documents\Audiveris\allegretto
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:767)
        at org.audiveris.omr.sheet.BookManager.getDefaultBookFolder(BookManager.java:409)
        at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:724)
        at org.audiveris.omr.CLI$CliTask.call(CLI.java:350)
        at org.audiveris.omr.Main.runBatchTasks(Main.java:316)
        at org.audiveris.omr.Main.main(Main.java:155)
        at Audiveris.main(Audiveris.java:49)
WARN  []                       CLI 821  | Exception occurred java.lang.NullPointerException
java.lang.NullPointerException: null
        at java.nio.file.Files.provider(Files.java:97)
        at java.nio.file.Files.exists(Files.java:2385)
        at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:728)
        at org.audiveris.omr.CLI$CliTask.call(CLI.java:350)
        at org.audiveris.omr.Main.runBatchTasks(Main.java:316)
        at org.audiveris.omr.Main.main(Main.java:155)
        at Audiveris.main(Audiveris.java:49)
WARN  []               BookManager 414  | Cannot create folder C:\Users\tehru\Documents\Audiveris\allegretto
java.nio.file.NoSuchFileException: C:\Users\tehru\Documents\Audiveris\allegretto
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:767)
        at org.audiveris.omr.sheet.BookManager.getDefaultBookFolder(BookManager.java:409)
        at org.audiveris.omr.sheet.BookManager.getDefaultSavePath(BookManager.java:466)
        at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:830)
        at org.audiveris.omr.CLI$CliTask.call(CLI.java:350)
        at org.audiveris.omr.Main.runBatchTasks(Main.java:316)
        at org.audiveris.omr.Main.main(Main.java:155)
        at Audiveris.main(Audiveris.java:49)
WARN  []                      Main 319  | Exception on allegretto, java.lang.NullPointerException
java.lang.NullPointerException: null
        at org.audiveris.omr.sheet.BookManager.getDefaultSavePath(BookManager.java:466)
        at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:830)
        at org.audiveris.omr.CLI$CliTask.call(CLI.java:350)
        at org.audiveris.omr.Main.runBatchTasks(Main.java:316)
        at org.audiveris.omr.Main.main(Main.java:155)
        at Audiveris.main(Audiveris.java:49)
WARN  []                      Main 190  | Exit forced. Failure

I have tried running Audiveris as an administrator, and have tried creating the folder manually, but a similar exception is raised noting that 'allegretto.omr' cannot be created.

Any help with this would be appreciated!

**Comment by ci7sta** [comment]
Changing the 'BaseFolder' setting of Audiveris to a different location fixed the issue.

**Comment by hbitteur** [comment]
@ci7sta 
Even though you closed the issue, I would like to understand what the problem was actually. Because changing the target location sounds like just a work around.

This reminds me of issue #271 which turned out to be caused by a trailing space in the name of the target folder.
This could apply to the BaseFolder as well, because Windows refuses to create a folder whose name ends with a space.
Could you check on your side?

Meanwhile, I will check in the code to protect against a misnaming of the base folder itself.

**Comment by hbitteur** [comment]
@ci7sta  
Could you tell us how you had set the base folder: 
- via the command line interface?
- or via the interactive options menu?

I suspect the second one, but please confirm.

**Comment by ci7sta** [comment]
Hi there,

I didn't set the base folder at all - it was the default location. Changing it to somewhere else via the interactive options menu fixed it for me. I will do a clean install again soon to see if the default location has a trailing space or similar.

**Comment by hbitteur** [comment]
I can't believe it.

In BookManager, could you undefine constant "**baseFolder**" in order to get back to default behavior.

I assume allegretto score is the one available in Audiveris examples, named "allegretto.png", therefore the target file should be in your case "C:\Users\tehru\Documents\Audiveris\allegretto\allegretto.omr" which will imply the creation of folder "C:\Users\tehru\Documents\Audiveris\allegretto" for all outputs related to allegretto score (.omr, .pdf, and others).
Check if an error occurs on folder creation when you try to save the result of allegretto transcription.

Then, modify the constant "**useSeparateBookFolders**" from true (the default) to false.
This time, transcription of "allegretto.png" should be stored into  "C:\Users\tehru\Documents\Audiveris\allegretto.omr" 
Mind the fact that the .omr file will be directly written into your Documents\Audiveris folder
Check if the error still occurs.

Thanks in advance for your feedback

**Comment by hbitteur** [comment]
I'm closing this issue, for lack of feedback
