### ISSUE TITLE
NullPointerException in LEDGERS step

### ISSUE THREAD

**Issue by rodrigoesborges** [Audiveris/audiveris#36]
I am not sure if this could be related to #25 , but I got this error when trying to transcribe a sheet from a pdf

WARN  [173633489-Sing-Sing-Sing-Score-PDF-July-29-2011-11-10-Am-389k#1]                 BasicStub 841  | Error in LEDGERS java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)                                                            
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)                                                               
        at org.audiveris.omr.sheet.BasicStub.doOneStep(BasicStub.java:824)                                                        
        at org.audiveris.omr.sheet.BasicStub.reachStep(BasicStub.java:564)                                                        
        at org.audiveris.omr.step.ui.StepMenu$StepAction$1.doInBackground(StepMenu.java:168)                                      
        at org.audiveris.omr.step.ui.StepMenu$StepAction$1.doInBackground(StepMenu.java:144)                                      
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)                                                                   
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                               
        at javax.swing.SwingWorker.run(SwingWorker.java:334)                                                                      
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                        
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                        
        at java.lang.Thread.run(Thread.java:748)                                                                                  
Caused by: java.lang.NullPointerException: null                                                                                   
INFO  [173633489-Sing-Sing-Sing-Score-PDF-July-29-2011-11-10-Am-389k#1]                 BasicStub 846  | Cause java.lang.NullPointerException                                                                                                                       
INFO  [173633489-Sing-Sing-Sing-Score-PDF-July-29-2011-11-10-Am-389k#1]                 BasicStub 571  | StepException detected in [LEDGERS]                                                                                                                        
INFO  [173633489-Sing-Sing-Sing-Score-PDF-July-29-2011-11-10-Am-389k#1]                  StepMenu 169  | End of sheet step LEDGERS

**Comment by maximumspatium** [comment]
In order to clarify the reason for this exception, I'll need to debug this concrete case. Can you grant me an access to the PDF in question somehow (via googledrive, wetransfer whatsoever)?
My email address is maximumspatium at googlemail.com
Thanks.

**Comment by hbitteur** [comment]
Please submit a concrete example we could work upon to reproduce the case and fix it

**Comment by maximumspatium** [comment]
Closing because of inactivity.
