### ISSUE TITLE
Audiveris fails to decompress tiff image data

### ISSUE THREAD

**Issue by deepio** [Audiveris/audiveris#374]
Could be related to: #201 

```bash
INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.0:4f234fefb
- OS:           Linux 4.19.76-linuxkit
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: [-batch, -export, -save, -output, /finished/, /to_do/achlieben_page9.tif]
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                      Main 147  | Running in batch mode
INFO  []                      Main 251  | Submitting 1 task(s) in sequence:
    Input "/to_do/achlieben_page9.tif"
INFO  [achlieben_page9]                      Book 473  | 1 sheet in /to_do/achlieben_page9.tif
INFO  []                      Book 1660 | Stored /book.xml
INFO  []                      Book 1613 | Book stored as /finished/achlieben_page9/achlieben_page9.omr
INFO  []                      Book 1327 | Book reaching PAGE on sheets:[#1]
INFO  [achlieben_page9]            StepMonitoring 93   | LOAD
WARN  [achlieben_page9]                 SheetStub 845  | Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1111)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:832)
        at org.audiveris.omr.sheet.Book.reachBookStep(Book.java:1393)
        at org.audiveris.omr.sheet.Book.transcribe(Book.java:1718)
        at org.audiveris.omr.sheet.Book.export(Book.java:591)
        at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:447)
        at org.audiveris.omr.CLI$CliTask.call(CLI.java:538)
        at org.audiveris.omr.Main.runBatchTasks(Main.java:312)
        at org.audiveris.omr.Main.main(Main.java:153)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.NullPointerException: null
        at com.github.jaiimageio.impl.plugins.tiff.TIFFLZWDecompressor.addStringToTable(TIFFLZWDecompressor.java:246)
        at com.github.jaiimageio.impl.plugins.tiff.TIFFLZWDecompressor.decode(TIFFLZWDecompressor.java:183)
        at com.github.jaiimageio.impl.plugins.tiff.TIFFLZWDecompressor.decodeRaw(TIFFLZWDecompressor.java:131)
        at com.github.jaiimageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2583)
        at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1144)
        at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1414)
        at javax.imageio.ImageReader.read(ImageReader.java:939)
        at org.audiveris.omr.image.ImageLoading$ImageIOLoader.getImage(ImageLoading.java:363)
        at org.audiveris.omr.sheet.Book.loadSheetImage(Book.java:1225)
        at org.audiveris.omr.step.LoadStep.doit(LoadStep.java:68)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1101)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1089)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
INFO  [achlieben_page9]                      Book 1660 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]                      Book 1613 | Book stored as /finished/achlieben_page9/achlieben_page9.omr
```
The same happens in the latest version on the master branch
```bash
INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.1:e51dc5f05
- OS:           Linux 4.19.76-linuxkit
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: [-batch, -export, -save, -output, /finished/, /to_do/achlieben_page9.tif]
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                      Main 147  | Running in batch mode
INFO  []                      Main 251  | Submitting 1 task(s) in sequence:
    Input "/to_do/achlieben_page9.tif"
INFO  [achlieben_page9]                      Book 473  | 1 sheet in /to_do/achlieben_page9.tif
INFO  []                      Book 1660 | Stored /book.xml
INFO  []                      Book 1613 | Book stored as /finished/achlieben_page9/achlieben_page9.omr
INFO  []                      Book 1327 | Book reaching PAGE on sheets:[#1]
INFO  [achlieben_page9]            StepMonitoring 93   | LOAD
WARN  [achlieben_page9]                 SheetStub 845  | Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1111)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:832)
        at org.audiveris.omr.sheet.Book.reachBookStep(Book.java:1393)
        at org.audiveris.omr.sheet.Book.transcribe(Book.java:1718)
        at org.audiveris.omr.sheet.Book.export(Book.java:591)
        at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:447)
        at org.audiveris.omr.CLI$CliTask.call(CLI.java:538)
        at org.audiveris.omr.Main.runBatchTasks(Main.java:312)
        at org.audiveris.omr.Main.main(Main.java:153)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.NullPointerException: null
        at com.github.jaiimageio.impl.plugins.tiff.TIFFLZWDecompressor.addStringToTable(TIFFLZWDecompressor.java:246)
        at com.github.jaiimageio.impl.plugins.tiff.TIFFLZWDecompressor.decode(TIFFLZWDecompressor.java:183)
        at com.github.jaiimageio.impl.plugins.tiff.TIFFLZWDecompressor.decodeRaw(TIFFLZWDecompressor.java:131)
        at com.github.jaiimageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2583)
        at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1144)
        at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1414)
        at javax.imageio.ImageReader.read(ImageReader.java:939)
        at org.audiveris.omr.image.ImageLoading$ImageIOLoader.getImage(ImageLoading.java:363)
        at org.audiveris.omr.sheet.Book.loadSheetImage(Book.java:1225)
        at org.audiveris.omr.step.LoadStep.doit(LoadStep.java:68)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1101)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1089)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
INFO  [achlieben_page9]                      Book 1660 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1246 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]                      Book 1613 | Book stored as /finished/achlieben_page9/achlieben_page9.omr
```
[achlieben_page9.tif.zip](https://github.com/Audiveris/audiveris/files/4495880/achlieben_page9.tif.zip)

If I convert the file to a PNG it seems to work, the accuracy is pretty good.

**Comment by deepio** [comment]
I don't know java, but the place where I saw the jaiimageio is related to tesseract here:
https://github.com/Audiveris/audiveris/blob/4f234fefb8a5e004f3b82fee11e68b57c004b20a/src/main/org/audiveris/omr/text/tesseract/TesseractOrder.java#L78-L80

My version of tesseract is
```bash
root@2a805fcd5017:/Audiveris/bin# tesseract --version
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
```

But according to Audiveris it says: `OCR Engine:   Tesseract OCR, version 3.04.01` which might be related?

**Comment by deepio** [comment]
I suppose it would need to be related because `TesseractOCR.getInstance().identify()` returns that version number.

https://github.com/Audiveris/audiveris/blob/4f234fefb8a5e004f3b82fee11e68b57c004b20a/src/main/org/audiveris/omr/Main.java#L348

**Comment by deepio** [comment]
I suppose it would need to be related because `TesseractOCR.getInstance().identify()` returns that version number.

https://github.com/Audiveris/audiveris/blob/4f234fefb8a5e004f3b82fee11e68b57c004b20a/src/main/org/audiveris/omr/Main.java#L348

https://github.com/Audiveris/audiveris/blob/4f234fefb8a5e004f3b82fee11e68b57c004b20a/src/main/org/audiveris/omr/text/tesseract/TesseractOCR.java#L149-L156

I don't know where its getting that version from, because everything should be 4.1.1
```bash
root@2a805fcd5017:/to_do# apt info libtesseract-dev
Package: libtesseract-dev
Version: 4.1.1-2build2
Priority: optional
Section: universe/libdevel
Source: tesseract
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Alexander Pozdnyakov <almipo@mail.ru>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 7691 kB
Depends: libtesseract4 (= 4.1.1-2build2), libleptonica-dev, libarchive-dev
Breaks: tesseract-ocr-dev (<< 3.0.1-1~)
Replaces: tesseract-ocr-dev (<< 3.0.1-1~)
Homepage: https://github.com/tesseract-ocr/
Download-Size: 1463 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
Description: Development files for the tesseract command line OCR tool
```

**Comment by deepio** [comment]
Does this need to be updated? 
https://github.com/Audiveris/audiveris/blob/2f64d06c1ac7671c40d6c597be36512162ab00ed/build.gradle#L118

**Comment by deepio** [comment]
Working with the `tess4` branch and updating jaiimageio produced some results. So I imagine the issue really is upstream with jaiimageio. 

```bash
INFO  []                      Main 334  | Environment:
- Audiveris:    5.2.0-alpha:9c4bcdd42
- OS:           Linux 4.19.76-linuxkit
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 25.252-b07, mixed mode)
- OCR Engine:   Tesseract OCR, version 4.0.0-rc3
INFO  []                       CLI 217  | CLI args: [-batch, -export, -save, -output, /finished/, /to_do/achlieben_page9.tif]
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                      Main 147  | Running in batch mode
INFO  []                      Main 251  | Submitting 1 task(s) in sequence:
    Input "/to_do/achlieben_page9.tif"
INFO  [achlieben_page9]                      Book 474  | 1 sheet in /to_do/achlieben_page9.tif
INFO  []                      Book 1663 | Stored /book.xml
INFO  []                      Book 1616 | Book stored as /finished/achlieben_page9/achlieben_page9.omr
INFO  []                      Book 1330 | Book reaching PAGE on sheets:[#1]
INFO  [achlieben_page9]            StepMonitoring 93   | LOAD
INFO  [achlieben_page9]                      Book 1227 | Loaded image 1 2894x4093 from /to_do/achlieben_page9.tif
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | BINARY
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                DataHolder 247  | Stored /sheet#1/BINARY.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | SCALE
INFO  [achlieben_page9]              ScaleBuilder 492  | Beam minHeight:5 maxHeight:15 quorum:4963
INFO  [achlieben_page9]                 ScaleStep 84   | Scale{line(1,3,5) interline(15,17,18) beam(14)}
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | GRID
INFO  [achlieben_page9]            LinesRetriever 447  | Global slope: -0.00048
INFO  [achlieben_page9]         ClustersRetriever 235  | Retrieved line clusters: 20 of size: 5 with interline: interline(15,17,18)
INFO  [achlieben_page9]                 PeakGraph 177  | Systems: #1[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] #2[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
INFO  [achlieben_page9]             BarsRetriever 1418 | System#1
INFO  [achlieben_page9]             BarsRetriever 1421 |    PartGroup{bracket number:1 barline:true staves:1-10}
INFO  [achlieben_page9]             BarsRetriever 1421 |    PartGroup{brace number:2 barline:true staves:1-2}
INFO  [achlieben_page9]             BarsRetriever 1421 |    PartGroup{brace number:2 barline:true staves:3-4}
INFO  [achlieben_page9]             BarsRetriever 1421 |    PartGroup{bracket number:2 barline:true staves:6-9}
INFO  [achlieben_page9]             BarsRetriever 1418 | System#2
INFO  [achlieben_page9]             BarsRetriever 1421 |    PartGroup{bracket number:1 barline:true staves:11-20}
INFO  [achlieben_page9]             BarsRetriever 1421 |    PartGroup{brace number:2 barline:true staves:11-12}
INFO  [achlieben_page9]             BarsRetriever 1421 |    PartGroup{brace number:2 barline:true staves:13-14}
INFO  [achlieben_page9]             BarsRetriever 1421 |    PartGroup{bracket number:2 barline:true staves:16-19}
INFO  [achlieben_page9]             SystemManager 731  | 10 parts along 2 systems
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | HEADERS
INFO  []           BasicClassifier 362  | Classifier loaded XML norms.
INFO  []        AbstractClassifier 348  | Classifier data loaded from default uri jar:file:/Audiveris/lib/audiveris.jar!/res/basic-classifier.zip
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | STEM_SEEDS
INFO  [achlieben_page9]             StemSeedsStep 93   | stem(2 max:4)
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | BEAMS
INFO  [achlieben_page9]            BlackHeadSizer 95   | Spots black-head retrieval diameter: 15.3
INFO  [achlieben_page9]            BlackHeadSizer 243  | Core black head count: 212 blackHead(width:19.4~0.5 height:19.6~1.0)
INFO  [achlieben_page9]            BlackHeadSizer 248  | MusicFont{name:MusicalSymbols pointSize:65}
INFO  [achlieben_page9]                 BeamsStep 86   | BeamDistance{count:85 mean:20.92 stdDev:8.77}
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                DataHolder 247  | Stored /sheet#1/HEAD_SPOTS.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | LEDGERS
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | HEADS
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | STEMS
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | REDUCTION
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | CUE_BEAMS
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]            StepMonitoring 93   | TEXTS
Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/deu.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'deu'
Failed loading language 'eng'
Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/fra.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'fra'
Tesseract couldn't load any languages!
WARN  [achlieben_page9]            TesseractOrder 178  | Could not initialize Tesseract with lang deu+eng+fra
WARN  [achlieben_page9]                 SheetStub 845  | Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1097)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:832)
        at org.audiveris.omr.sheet.Book.reachBookStep(Book.java:1396)
        at org.audiveris.omr.sheet.Book.transcribe(Book.java:1721)
        at org.audiveris.omr.sheet.Book.export(Book.java:592)
        at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:455)
        at org.audiveris.omr.CLI$CliTask.call(CLI.java:549)
        at org.audiveris.omr.Main.runBatchTasks(Main.java:312)
        at org.audiveris.omr.Main.main(Main.java:153)
        at Audiveris.main(Audiveris.java:47)
Caused by: java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(ArrayList.java:581)
        at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:80)
        at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:42)
        at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:98)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1087)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1075)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
INFO  [achlieben_page9]                      Book 1454 | Scores built: 1
INFO  [achlieben_page9]             ScoreExporter 88   | Score achlieben_page9 exported to /finished/achlieben_page9/achlieben_page9.mxl
INFO  [achlieben_page9]                      Book 1663 | Stored /book.xml
INFO  [achlieben_page9]                     Sheet 1249 | Stored /sheet#1/sheet#1.xml
INFO  [achlieben_page9]                      Book 1616 | Book stored as /finished/achlieben_page9/achlieben_page9.omr
```

**Comment by deepio** [comment]
Solution: 
- Use `tess4` branch
- Update jaiimageio to `1.4.0`

`TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata /Audiveris/bin/Audiveris -batch -export -save -output ...`

But it will still fail to generate output properly for a different reason. Will create a new issue for that.

**Comment by hbitteur** [comment]
@deepio 
Current Audiveris version (either master or development branches) requires Tesseract 3.04.
Don't waste your time trying to use Tesseract 4 from Audiveris.

According to your messages, you have Tesseract 4 installed. Hence the messages:
> tesseract --version
> tesseract 4.1.1

But keep in mind that Tesseract library (3.04) is accessed directly from Audiveris, whether or not you have Tesseract installed, in whatever version. This explains why the Tesseract version as printed by Audiveris is different from your installed Tesseract version.

For Audiveris, all you need is to make sure you have proper Tesseract **data** files, not binary files.

**Comment by deepio** [comment]
@hbitteur the thing I find very odd is that audiveris always worked for PNG images, but not on TIFF because of those crashes I experienced. That's why I included the tiff file I was using in the first comment if you're curious to try it. I can convert tiffs to pngs and it would work fine. But i'm trying to compare multiple OMR software and if I change the format for one OMR then others might believe that the OMR in question had an advantage/disadvantage over the others.

**Comment by hbitteur** [comment]
According to the stack trace printed at the beginning of this issue, the exception is raised in some plugin of jaiimageio (JAI software) when processing the tiff file:
> com.github.jaiimageio.impl.plugins.tiff.TIFFLZWDecompressor.addStringToTable(TIFFLZWDecompressor.java:246)

I'm afraid there is nothing we can do at Audiveris level to fix this. Perhaps you can submit the issue with your concrete example to JAI (Java Advanced Imaging) project.

As a user, you can still work around this bug by converting this tiff file to some other format, as you did.

**Comment by deepio** [comment]
Yes, that is what I think I will do for now until jaiimageio updates. Thank you for your time!
