### ISSUE TITLE
Error when trying to call Audiveris from php exec()

### ISSUE THREAD

**Issue by ShayneMn** [Audiveris/audiveris#383]
Sorry if this isn't the place for this. But I am trying to call Audiveris from within my PHP file with PHP's exec() function. 

``exec(java -cp "Audiveris/lib/*" Audiveris -batch -export  -- '.$sheet_music_path);``

All paths are correct and I can run other java programs fine with this command. When I run this command in command prompt I get no issues. However, when I execute it within PHP I get the following error.
```
May 02, 2020 6:02:37 PM sun.awt.shell.Win32ShellFolderManager2 getPersonal
WARNING: Cannot access 'Personal'
java.io.IOException: Could not get shell folder ID list
	at sun.awt.shell.Win32ShellFolder2.getFileSystemPath0(Native Method)
	at sun.awt.shell.Win32ShellFolder2.access$800(Unknown Source)
	at sun.awt.shell.Win32ShellFolder2$7.call(Unknown Source)
	at sun.awt.shell.Win32ShellFolder2$7.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

May 02, 2020 6:02:37 PM sun.awt.shell.Win32ShellFolderManager2 getDesktop
WARNING: Cannot access 'Desktop'
java.io.IOException: Could not get shell folder ID list
	at sun.awt.shell.Win32ShellFolder2.getFileSystemPath0(Native Method)
	at sun.awt.shell.Win32ShellFolder2.access$800(Unknown Source)
	at sun.awt.shell.Win32ShellFolder2$7.call(Unknown Source)
	at sun.awt.shell.Win32ShellFolder2$7.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.audiveris.omr.Main.<clinit>(Main.java:64)
	at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.NullPointerException
	at org.audiveris.omr.WellKnowns.getFolderForWindows(WellKnowns.java:403)
	at org.audiveris.omr.WellKnowns.getFolder(WellKnowns.java:302)
	at org.audiveris.omr.WellKnowns.<clinit>(WellKnowns.java:141)
	... 2 more
```

Any help with this issue will be greatly appreciated.
I am using Windows 10, jdk8 and installed Audiveris using the windows x64 executable

**Comment by hbitteur** [comment]
@ShayneMn 
Here is the Java line in Audiveris application where a NullPointerException is thrown:
> final String userDocs = FileSystemView.getFileSystemView().getDefaultDirectory().getPath();

This is supposed to report the default directory of your file system as seen by your application.
I'm not at all familiar with PHP, but it looks like you cannot access some file location.
I cannot help you further.

**Comment by hbitteur** [comment]
@ShayneMn 
Could you share with us if (and how) you could fix the problem?
