### ISSUE TITLE
Unable to run Audiveris

### ISSUE THREAD

**Issue by Sunny090628** [Audiveris/audiveris#386]
When I open Audiveris, the command window pops up for a second and then is gone.

**Comment by hbitteur** [comment]
Could you tell us more about the context.
Windows, Linux or MacOS?
How did you launch the application?

Try the following:
- Open a command prompt window (Search for cmd.exe if you are on Windows)
- Then, from this command window, navigate (cd) to where you installed Audiveris software.
- You should have a "build" subfolder  with a "scripts" subsubfolder, containing two scripts: "Audiveris" and "Audiveris.bat". Use the former on Linux & Mac, the latter on Windows.
- Launch the proper script and observe the error messages if any in this window.

Please post your messages here so that we can see what happened.

**Comment by krzysztofciombor** [comment]
I have a similar issue. Here's the output of running Audiveris from Command Line:
```
C:\Program Files\Audiveris\bin>Audiveris.bat
INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.0:4687c3527
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: []
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:124)
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:112)
        at org.audiveris.omr.sheet.BookManager$LazySingleton.<clinit>(BookManager.java:467)
        at org.audiveris.omr.sheet.BookManager.getInstance(BookManager.java:458)
        at org.audiveris.omr.Main.main(Main.java:138)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 6 more
```
The problem (based on https://stackoverflow.com/a/43574427) is most likely caused by the fact that I'm using Java VM 12

**Comment by hbitteur** [comment]
I can confirm that Audiveris 5.1.0 release requires Java 7 or 8.
Starting with Java 9, JAXB was no longer bundled by default in Java runtime.

I'd suggest to download and build the "development" branch of Audiveris. In addition to many application improvements, you could thus use Java 11 (I don't know yet for Java 12).

**Comment by Sunny090628** [comment]
`C:\Program Files\Audiveris\bin>Audiveris.bat
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:613)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.lept.<clinit>(lept.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.load(Loader.java:585)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.tesseract$TessBaseAPI.<clinit>(tesseract.java:3648)
        at org.audiveris.omr.text.tesseract.TesseractOCR.identify(TesseractOCR.java:152)
        at org.audiveris.omr.Main.showEnvironment(Main.java:348)
        at org.audiveris.omr.Main.main(Main.java:122)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.UnsatisfiedLinkError: no liblept in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:604)
        ... 11 more`
With Java 8 running

**Comment by hbitteur** [comment]
This sounds like a mismatch between 32 and 64-bit architecture
Could you make sure that Audiveris software and the Java environment used at runtime are both 32-bit or both 64-bit. Beware, this match is not enforced by the Audiveris Windows installer.

**Comment by Schrankee** [comment]
> This sounds like a mismatch between 32 and 64-bit architecture
> Could you make sure that Audiveris software and the Java environment used at runtime are both
> 32-bit or both 64-bit. Beware, this match is not enforced by the Audiveris Windows installer.

That is correct. I had the same issue while i accidentaly downloaded 32-bit Java,

**Comment by Sunny090628** [comment]
works!
