### ISSUE TITLE
Cannot install audiveris on Windows:  BasicTest. initializationError

### ISSUE THREAD

**Issue by v-forman** [Audiveris/audiveris#39]
Hi,
I tried installing audiveris on Windows, closely following the steps given on the main github page. But it wont work. Here are the test results after the command "gradle build":

179 tests     7 failures     0 ignored     2.201s duration
    BasicTest. initializationError
    TestFacade. initializationError
    TestCompound. initializationError
    TestEntity. initializationError
    TestRefs. initializationError
    TableTest. initializationError
    RunTableBindingTest. initializationError

Here are the details on initializationError (sorry it's long):
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3139)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3280)
	at java.base/java.lang.Class.getMethod0(Class.java:3266)
	at java.base/java.lang.Class.getMethod(Class.java:2063)
	at org.junit.internal.builders.SuiteMethodBuilder.hasSuiteMethod(SuiteMethodBuilder.java:20)
	at org.junit.internal.builders.SuiteMethodBuilder.runnerForClass(SuiteMethodBuilder.java:13)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 40 more

When I try "gradle run", I also get an error (which seems to be the same):
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:128)
        at org.audiveris.omr.sheet.BookManager.getInstance(BookManager.java:313)
        at org.audiveris.omr.Main.main(Main.java:140)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 4 more

Could anyone help me?

Best regards,
Vincent

**Comment by v-forman** [comment]
By the way, I'm not sure if it is related, but I installed a precompiled version of Tesseract with the recommended data files. Could it be that it somehow cannot figure the location of Tesseract?

**Comment by maximumspatium** [comment]
Does `gradle clean run` work?
Can you run `java -version` and `gradle -v` in your command prompt and post the result here?

**Comment by LordAskh** [comment]
Hello maxim,

I'm currently having the same issue as Vincent, with the following tests failing:
BasicTest. initializationError
TestFacade. initializationError
TestCompound. initializationError
TestEntity. initializationError
TestRefs. initializationError
TableTest. initializationError
RunTableBindingTest. initializationError

Gradle clean run fails and directs me to reports/tests/test where I found out which tests were failing (the seven mentioned above).
The screenshots below show the build failure and the result of running java-version and gradle -v
![capture1](https://user-images.githubusercontent.com/6130699/33605752-aae4810e-d9c3-11e7-928d-e95180e8cffe.PNG)
![capture2](https://user-images.githubusercontent.com/6130699/33605753-aafece9c-d9c3-11e7-897d-c06c15274a36.PNG)

Looking forward to your reply,

Andrei.

**Comment by maximumspatium** [comment]
Hello Andrei,

Audiveris doesn't work with JDK9. The problem with Java is that each new JDK version adds some incompatibility with the previous one (we have recently fixed our Javadoc to work with JDK8).

I hope we'll find some time to work around this issue with JDK9.

For the moment being, you'll need to install JDK8. 

Sorry for the inconvenience.

**Comment by Andrei-UPB** [comment]
Thank you for the quick answer, I will install the required version of JDK and be back with a reply of wether it worked or not.

**Comment by v-forman** [comment]
Thank you for the quick answer, it worked for me also! Now to figure out how to export for denemo...
