### ISSUE TITLE
No music in exported book/sheet

### ISSUE THREAD

**Issue by contrapunctus-1** [Audiveris/audiveris#418]
I've been trying to get Audiveris to scan [this file](https://imslp.org/wiki/File:Schubert_-_Die_Schone_Mullerin.pdf) on a Debian Testing system. Transcribing the book or a sheet results in music data being displayed in color, but when I export it, the output MXL archive has no musical data.

1. I open the file in Audiveris
2. Transcribe sheet/Transcribe book
3. Export sheet as/Export book as/Save book
4. Open the file from the archive in a text editor.
(I chanced upon this by running musicxml2ly on the resulting MXL file.)

I see some Tesseract errors. The handbook says that I need Tesseract 3.04, but Debian Testing only has 4.0. At any rate, the handbook seems to say that Tesseract is only for text, so I don't know if it's related to the MXL output not containing any music.

Terminal output -
```
$ JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/ ./gradlew run     

> Configure project : 
targetOS=linux-x86_64

> Task :run 
INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.1:5e15ef8ca
- OS:           Linux 5.7.0-1-amd64
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: []
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                   MainGui 499  | Audiveris version 5.1.1
INFO  []                   MainGui 500  | 
LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No /home/anon/.config/AudiverisLtd/audiveris/logback.xml, skipped.
LogUtil. Configuration found file:///home/anon/git/audiveris/res/logback.xml
LogUtil. Logging to /home/anon/.cache/AudiverisLtd/audiveris/log/20200822T135156.log

INFO  []           BasicClassifier 362  | Classifier loaded XML norms.
INFO  []        AbstractClassifier 348  | Classifier data loaded from default uri file:///home/anon/git/audiveris/res/basic-classifier.zip
INFO  []            PluginsManager 235  | No /home/anon/.config/AudiverisLtd/audiveris/plugins.xml file found
INFO  []               BookManager 194  | Found alias: IMSLP00412 for IMSLP00412-Schubert_-_Die_Schone_Mullerin
INFO  [IMSLP00412]                      Book 473  | 50 sheets in /path/to/IMSLP00412-Schubert_-_Die_Schone_Mullerin.pdf
INFO  [IMSLP00412#1]                      Book 1226 | Loaded image 1 2708x3883 from /path/to/IMSLP00412-Schubert_-_Die_Schone_Mullerin.pdf
INFO  [IMSLP00412#1]              ScaleBuilder 492  | Beam minHeight:9 maxHeight:20 quorum:2413
INFO  [IMSLP00412#1]                 ScaleStep 84   | Scale{line(4,6,9) interline(20,22,24) beam(14)}
INFO  [IMSLP00412#1]            LinesRetriever 447  | Global slope: -0.00073
INFO  [IMSLP00412#1]         ClustersRetriever 786  | Pairing clusters CC269 & CC219
INFO  [IMSLP00412#1]         ClustersRetriever 235  | Retrieved line clusters: 9 of size: 5 with interline: interline(20,22,24)
INFO  [IMSLP00412#1]                 PeakGraph 177  | Systems: #1[1, 2, 3] #2[4, 5, 6] #3[7, 8, 9]
INFO  [IMSLP00412#1]             SystemManager 648  | Indentation detected for system#1
INFO  [IMSLP00412#1]             SystemManager 731  | 2 parts along 3 systems
INFO  [IMSLP00412#1]                KeyBuilder 906  | Staff#8 key replication failed.
INFO  [IMSLP00412#1]                StemScaler 177  | No stem peak found, computing defaults
INFO  [IMSLP00412#1]             StemSeedsStep 93   | stem(6 max:9)
INFO  [IMSLP00412#1]            BlackHeadSizer 95   | Spots black-head retrieval diameter: 19.8
INFO  [IMSLP00412#1]            BlackHeadSizer 243  | Core black head count: 52 blackHead(width:30.7~0.4 height:26.7~0.9)
INFO  [IMSLP00412#1]            BlackHeadSizer 248  | MusicFont{name:MusicalSymbols pointSize:103}
INFO  [IMSLP00412#1]                 BeamsStep 86   | BeamDistance{count:63 mean:14.92 stdDev:10.26}
Failed loading language 'deu'
Failed loading language 'eng'
Failed loading language 'fra'
Tesseract couldn't load any languages!
WARN  [IMSLP00412#1]            TesseractOrder 166  | Could not initialize Tesseract with lang deu+eng+fra
WARN  [IMSLP00412#1]                 SheetStub 845  | Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1111)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:832)
        at org.audiveris.omr.sheet.SheetStub.transcribe(SheetStub.java:1026)
        at org.audiveris.omr.sheet.ui.BookActions$TranscribeSheetTask.doInBackground(BookActions.java:2094)
        at org.audiveris.omr.sheet.ui.BookActions$TranscribeSheetTask.doInBackground(BookActions.java:2077)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(ArrayList.java:583)
        at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:80)
        at org.audiveris.omr.text.TextsStep.doProlog(TextsStep.java:42)
        at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:98)
        at org.audiveris.omr.step.Step.doit(Step.java:184)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1101)
        at org.audiveris.omr.sheet.SheetStub$4.call(SheetStub.java:1089)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 common frames omitted


BUILD SUCCESSFUL in 2m 15s
5 actionable tasks: 3 executed, 2 up-to-date
```

**Comment by contrapunctus-1** [comment]
@hbitteur , thanks a lot for telling me about useOCR - I finally got in music in the output file! 🙂

Is there any ongoing work on making Audiveris work with Tesseract 4? I could certainly install Tesseract 3 from source, but I'd prefer that Audiveris work for all users without requiring that, especially on a ubiquitous distro like Debian.

Also, please let me know if there's any issue I could let the Debian Tesseract maintainers know of.

**Comment by hbitteur** [comment]
Tesseract 4 is almost unusable with OMR.
This is why Audiveris still uses Tesseract 3.

I think I remember there is a way to make Tesseract 4 use a "legacy" mode whereby Tesseract 3 engine is used. I will have to search in old discussions for the precise way to do this.

This should solve your problem with available Debian packages.

**Comment by contrapunctus-1** [comment]
I see...

Is it this?

> Use --oem 1 for LSTM, --oem 0 for Legacy Tesseract. Please note that Legacy Tesseract models are only included in traineddata files from tessdata repo.
> `tesseract input.tiff output --oem 1 -l eng`

https://tesseract-ocr.github.io/tessdoc/Command-Line-Usage.html

**Comment by hbitteur** [comment]
Yes, this is it.
