### ISSUE TITLE
Having issues on latest version (window 10)

### ISSUE THREAD

**Issue by YuenSzeHong** [Audiveris/audiveris#466]
having an error of running the latest version.
`INFO  []                      Main 334  | Environment:
- Audiveris:    5.1.0:4687c3527
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 217  | CLI args: []
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:124)
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:112)
        at org.audiveris.omr.sheet.BookManager$LazySingleton.<clinit>(BookManager.java:467)
        at org.audiveris.omr.sheet.BookManager.getInstance(BookManager.java:458)
        at org.audiveris.omr.Main.main(Main.java:138)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 6 more`

**Comment by hbitteur** [comment]
> java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
My understanding is that Java VM did not find JAXBException class. How come?

This is certainly related to the fact that you launched Audiveris on Java 14:
> Java VM: Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

Starting with Java 9, the Java platform is now more modular. Typically, JAXB is one of the Java features that are no longer included by default.

5.1 version requires Java 8.
5.2 version is being developed on Java 11 (it may work with Java 14, I don't know yet).

So, you have two possibilities:
- Use Java 8 (instead of 14) to launch Audiveris 5.1 ("master" branch, this is your version)
- Pull and build branch "development" of Audiveris (5.2-alpha) with Java 11 (or perhaps 14)

**Comment by YuenSzeHong** [comment]
thanks for pointing out, sorry for not noticing that.
