### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by soundnotation** [Audiveris/audiveris#47]
I got Gradle and Tesseract (`tesseract-ocr`) installed, plus I have the latest Java 8 build. I am running Ubuntu 16.04.
Nonetheless, while trying to build Audiveris (on its `development` branch), it fails at the task `:test`.

`$ gradle clean build`

```
> Configure project :
targetOS=linux-x86_64

Download https://jcenter.bintray.com/org/jgrapht/jgrapht-core/1.0.1/jgrapht-core-1.0.1.pom
Download https://jcenter.bintray.com/org/jgrapht/jgrapht/1.0.1/jgrapht-1.0.1.pom
Download https://jcenter.bintray.com/org/jgrapht/jgrapht-core/1.0.1/jgrapht-core-1.0.1.jar

> Task :compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Download https://jcenter.bintray.com/org/jgrapht/jgrapht-ext/1.0.1/jgrapht-ext-1.0.1.pom
Download https://jcenter.bintray.com/org/jgrapht/jgrapht-ext/1.0.1/jgrapht-ext-1.0.1.jar

> Task :compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: /home/soundnotation/audiveris/src/test/org/audiveris/omr/ui/symbol/MusicFontTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :test

org.audiveris.omr.ui.ZoomTest > testZoom FAILED
    java.awt.HeadlessException at ZoomTest.java:60

org.audiveris.omr.ui.MouseWheelTest > play FAILED
    java.awt.HeadlessException at MouseWheelTest.java:102

186 tests completed, 2 failed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/soundnotation/audiveris/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
11 actionable tasks: 11 executed
```

`$ gradle -v`

```
------------------------------------------------------------
Gradle 4.5
------------------------------------------------------------

Build time:   2018-01-24 17:04:52 UTC
Revision:     77d0ec90636f43669dc794ca17ef80dd65457bec

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Linux 4.4.0-104-generic amd64
```

`$ tesseract -v`
```
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.2
```

`$ java -version`
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

Moreover, if I try `gradle clean run`, it goes like:

```
> Configure project :
targetOS=linux-x86_64

> Task :compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :run
LogUtil. Property logback.configurationFile not defined.
LogUtil. No /home/soundnotation/.config/AudiverisLtd/audiveris/logback.xml
LogUtil. Config file:///home/soundnotation/audiveris/res/logback.xml
INFO  []                       CLI 206  | CLI args: []
LogUtil. Logging to /home/soundnotation/.cache/AudiverisLtd/audiveris/log/20180125T170816.log
INFO  []                      Main 338  | Environment:
- Audiveris:    5.1.0:1be12f4
- OS:           Linux 4.4.0-104-generic
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []             AliasPatterns 143  | Alias patterns: [(IMSLP[0-9]*)-.*]
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at org.jdesktop.application.ResourceMap.<clinit>(ResourceMap.java:1354)
        at org.jdesktop.application.ResourceManager.createResourceMap(ResourceManager.java:468)
        at org.jdesktop.application.ResourceManager.createResourceMapChain(ResourceManager.java:151)
        at org.jdesktop.application.ResourceManager.createResourceMapChain(ResourceManager.java:150)
        at org.jdesktop.application.ResourceManager.getApplicationResourceMap(ResourceManager.java:170)
        at org.jdesktop.application.ResourceManager.getResourceMap(ResourceManager.java:307)
        at org.jdesktop.application.ApplicationContext.getResourceMap(ApplicationContext.java:206)
        at org.jdesktop.application.Application.create(Application.java:250)
        at org.jdesktop.application.Application$1.run(Application.java:185)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:236)
        at org.jdesktop.application.ResourceMap$KeyStrokeStringConverter.<clinit>(ResourceMap.java:1511)
        ... 23 more
```

**Comment by maximumspatium** [comment]
> No X11 DISPLAY variable was set

That tells the exact reason for Audiveris doesn't start. You need to run this from within a X11 environment to work. Either you're trying to run it outside the X environment or your Java installation wasn't configured properly. See [this thread](https://ubuntuforums.org/showthread.php?t=1733291) for the starting point...

**Comment by maximumspatium** [comment]
@soundnotation Did you solved your problem? Can I close this issue?

**Comment by soundnotation** [comment]
So the issue seems related to the fact that Audiveris needs a GUI, doesn't it? Since my machine is a remote VM, connecting to it with mobaxterm solved the problem, in the sense that, as I fired `gradle clean run` from there, it opened up the interface. Is there no way we can run Audiveris outside the GUI, i.e. CLI instructions?

**Comment by soundnotation** [comment]
Pardon my previous comment, I'm still having a look at the wiki and I found out that it's possible with CLI.
One thing to clarify: an X11 environment is only needed to build or run the program, right?

**Comment by maximumspatium** [comment]
> One thing to clarify: an X11 environment is only needed to build or run the program, right?

Audiveris can be used as a pure CLI program. But the build process currently relies on Swing (and in turn on X11) because some old tests (like [mouseWheelTest](https://github.com/Audiveris/audiveris/blob/master/src/test/org/audiveris/omr/ui/MouseWheelTest.java)) do.
IIRC, the build can be decoupled from a graphical environment by manually removing the `test/org/audiveris/omr/ui/` package...

@hbitteur Do we need these UI tests?

**Comment by hbitteur** [comment]
No, we don't really need them.
These are old stuff.
I think that all ui tests could simply be deleted.
Since they are even harmful for certain environments, we should not hesitate.

**Comment by hbitteur** [comment]
OK, I just removed all unitary tests where Java Swing was involved.

**Comment by maximumspatium** [comment]
@soundnotation 
Here we go: a1f1e3b
Could you switch to development branch and try to build Audiveris without X11? Thanks.

**Comment by soundnotation** [comment]
I can confirm running from development branch from a simple bash console works now
