### ISSUE TITLE
java.lang.NullPointerException: null at org.audiveris.omr.sheet.ui.SheetPainter$SigPainter.<init> on opening PDF

### ISSUE THREAD

**Issue by hallvors** [Audiveris/audiveris#483]
Up-to-date development branch can not open this file:
[Klarinett 3.pdf](https://github.com/Audiveris/audiveris/files/6276944/Klarinett.3.pdf)

Not sure if this bug is in Audiveris or whatever component you use for PDFs, but this is the stack:

WARN  []               RubberPanel 710  | RubberPanel paintComponent java.lang.NullPointerException
java.lang.NullPointerException: null
        at org.audiveris.omr.sheet.ui.SheetPainter$SigPainter.<init>(SheetPainter.java:474)
        at org.audiveris.omr.sheet.ui.SheetResultPainter$ResultSigPainter.<init>(SheetResultPainter.java:408)
        at org.audiveris.omr.sheet.ui.SheetResultPainter.getSigPainter(SheetResultPainter.java:280)
        at org.audiveris.omr.sheet.ui.SheetPainter.process(SheetPainter.java:228)
        at org.audiveris.omr.sheet.ui.PictureView$MyView.doRender(PictureView.java:227)
        at org.audiveris.omr.sheet.ui.PictureView$MyView.render(PictureView.java:176)
        at org.audiveris.omr.ui.view.RubberPanel.paintComponent(RubberPanel.java:701)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1024)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
        at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by hallvors** [comment]
Hm.. after restarting Audiveris it opened just fine.

**Comment by hallvors** [comment]
.. but this happened: _java.lang.RuntimeException: org.audiveris.omr.math.Line$UndefinedLineException: Not enough defining points: 0_

**Comment by hallvors** [comment]
This might be the problem?
![Skjermbilete_2021-04-08_09-54-42](https://user-images.githubusercontent.com/120136/113989173-79035800-9850-11eb-85f4-a66ca854c8c2.png)

**Comment by hbitteur** [comment]
Bug fixed in commit bb7b7b2257ec4e7b484c880cb9c4b1e6de43726d
Please pull again development branch

**Comment by hallvors** [comment]
Verified, no null pointer exception now. (I wonder if it detects fewer beams though)
