### ISSUE TITLE
Audiveris won't open

### ISSUE THREAD

**Issue by chenlung** [Audiveris/audiveris#506]
The command window appears very briefly but Audiveris 5.2 doesn't open when clicking the icon.

AMD FX(tm)-6300 Six-Core Processor                3.50 GHz
64-bit operating system, x64-based processor
Windows 10 Home

```
C:\Users\[name]>"C:\Program Files\Audiveris\bin\Audiveris.bat"
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Audiveris has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by chenlung** [comment]
Any help appreciated. Thank you.

**Comment by hbitteur** [comment]
What is your installed Java version?
Use command:
> java -version

(Current Audiveris 5.2.3 requires Java 11)

**Comment by chenlung** [comment]
> What is your installed Java version?
> Use command:
> 
> > java -version
> 
> (Current Audiveris 5.2.3 requires Java 11)

`java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)`

**Comment by hbitteur** [comment]
So, you have to install Java 11 instead of Java 8

**Comment by chenlung** [comment]
Thank you, Hervé!
