### ISSUE TITLE
Audiveris Crashes on start

### ISSUE THREAD

**Issue by nolhananas** [Audiveris/audiveris#511]
Hi.
I've installed the audiveris main branch via the windows_64x installer, and I have been trying to make it work for a couple of minutes now.
I have read all the issues corresponding to my situation, but none of the solutions seemed to work.

Here is my version of Java :
```
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)
```

And here is the error message I get while trying to launch the batch file via cmd :
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Audiveris has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

How could i fix this ?

**Comment by hbitteur** [comment]
Audiveris 5.2.x needs Java 11, and you tried to launch it with Java 8.
So please install Java 11

**Comment by nolhananas** [comment]
> Audiveris 5.2.x needs Java 11, and you tried to launch it with Java 8.
> So please install Java 11

Well, I already tried downloading Java 11, but I can only find the JDKs and never the JREs...
Do you have a link to download Java 11 specifically ? that would help !

**Comment by hbitteur** [comment]
I think you are right. You might be interested by this discussion: [https://stackoverflow.com/questions/53733312/where-is-jre-11](https://stackoverflow.com/questions/53733312/where-is-jre-11)

**Comment by hbitteur** [comment]
Have you installed the JDK 11?

**Comment by thevbw** [comment]
bump, same error after installing jdk 17 from oracle

**Comment by hbitteur** [comment]
Please provide enough information so that we can understand what is happening:
- OS environment
- Java environment
- Audiveris version
- The whole log of messages printed

**Comment by nolhananas** [comment]
thank you !
