### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by severine-baudry** [Audiveris/audiveris#516]
I installed the windows binaries for Audiveris, as well as java (version jdk-11.0.11). When launching Audiveris, I got the following error message :
`
INFO  []                      Main 338  | Environment:
- Audiveris:    5.1.0:9fa751d43
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 11.0.11+9-LTS-194, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 206  | CLI args: []
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.audiveris.omr.sheet.BookManager.<init>(BookManager.java:128)
        at org.audiveris.omr.sheet.BookManager.getInstance(BookManager.java:313)
        at org.audiveris.omr.Main.main(Main.java:140)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
`

Should I install an additional library ?
Thanks,

**Comment by hbitteur** [comment]
The JAXB exception comes from the fact that, starting with Java 9, JAXB is no longer included by default.

You are trying to use Audiveris 5.1.x which required Java 8 (JAXB was included in Java 8) and you have Java 11 instead.
So, you have a choice:
- Either install Java 8 instead of Java 11 and stay with Audiveris 5.1.x
- Or keep Java 11 and download latest Audiveris version (5.2.4) which requires Java 11.

I'd suggest to do the latter.

**Comment by hbitteur** [comment]
Any news?
Can we close this issue.

**Comment by severine-baudry** [comment]
Thanks that works perferct; you can close the issue

Le mar. 9 nov. 2021 à 10:36, Hervé Bitteur ***@***.***> a
écrit :
