### ISSUE TITLE
Audiveris not opening properly

### ISSUE THREAD

**Issue by Chrononology** [Audiveris/audiveris#544]
It only opens for a split second
Heres what I got when I tried to open the .bat file in the cmd:

C:\Program Files\Audiveris\bin>Audiveris.bat
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Audiveris has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
        
        Chrononology

**Comment by Chrononology** [comment]
I installed it in the program files folder rather than d: drive

**Comment by hbitteur** [comment]
Could you tell us:
- OS (Windows I suppose from the .bat)
- Which Java version is installed on your machine
- Did you use the Windows installer, or rebuilt software on your own

We have just switched to Java 17 (see the warning posted on Audiveris github page) at least for the "development" branch.
This should explain your error messages.

Please keep us informed.

**Comment by Chrononology** [comment]
@hbitteur

1. I used the windows installer
2. Just noticed that my Java version is outdated. 
thanks for the help!
