### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when running chula example

### ISSUE THREAD

**Issue by guillaumerose** [Audiveris/audiveris#547]
When running chula example in data/examples + development branch, I got:

```
audiveris-converter  | INFO  [chula]            StepMonitoring 96   | CURVES
audiveris-converter  | WARN  [chula]                 SheetStub 1048 | Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 4788832 out of bounds for length 4787300
audiveris-converter  | java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 4788832 out of bounds for length 4787300
audiveris-converter  | 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
audiveris-converter  | 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
audiveris-converter  | 	at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1346)
audiveris-converter  | 	at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:1032)
audiveris-converter  | 	at org.audiveris.omr.sheet.Book.reachBookStep(Book.java:1765)
audiveris-converter  | 	at org.audiveris.omr.sheet.Book.transcribe(Book.java:2128)
audiveris-converter  | 	at org.audiveris.omr.sheet.Book.export(Book.java:524)
audiveris-converter  | 	at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:549)
audiveris-converter  | 	at org.audiveris.omr.CLI$CliTask.call(CLI.java:643)
audiveris-converter  | 	at org.audiveris.omr.Main.runBatchTasks(Main.java:379)
audiveris-converter  | 	at org.audiveris.omr.Main.main(Main.java:167)
audiveris-converter  | 	at Audiveris.main(Audiveris.java:49)
audiveris-converter  | Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4788832 out of bounds for length 4787300
audiveris-converter  | 	at ij.process.ByteProcessor.get(ByteProcessor.java:251)
audiveris-converter  | 	at org.audiveris.omr.sheet.curve.JunctionRetriever.dirNeighbors(JunctionRetriever.java:136)
audiveris-converter  | 	at org.audiveris.omr.sheet.curve.JunctionRetriever.vicinityOf(JunctionRetriever.java:199)
audiveris-converter  | 	at org.audiveris.omr.sheet.curve.JunctionRetriever.checkJunction(JunctionRetriever.java:102)
audiveris-converter  | 	at org.audiveris.omr.sheet.curve.JunctionRetriever.scanImage(JunctionRetriever.java:81)
audiveris-converter  | 	at org.audiveris.omr.sheet.curve.Curves.buildCurves(Curves.java:128)
audiveris-converter  | 	at org.audiveris.omr.sheet.curve.CurvesStep.doit(CurvesStep.java:53)
audiveris-converter  | 	at org.audiveris.omr.step.OmrStep.doit(OmrStep.java:185)
audiveris-converter  | 	at org.audiveris.omr.sheet.SheetStub.lambda$doOneStep$4(SheetStub.java:1331)
audiveris-converter  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
audiveris-converter  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
audiveris-converter  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
audiveris-converter  | 	at java.base/java.lang.Thread.run(Thread.java:833)
``` 

I used the following docker image to run it: https://github.com/weidi/audiveris-docker/pull/5

**Comment by hbitteur** [comment]
Fixed by commit 4dd88b6b53efc641003d29595284df92fd3f66fc in development branch
