### ISSUE TITLE
'no such vertex in graph' error when running zizi example

### ISSUE THREAD

**Issue by guillaumerose** [Audiveris/audiveris#548]
When running zizi example in data/examples + development branch, I got multiple exceptions:

```
audiveris-converter  | INFO  [zizi]            StepMonitoring 96   | PAGE
audiveris-converter  | WARN  [zizi]                     Voice 300  | Error checking Measure{#6P1} duration java.lang.IllegalArgumentException: no such vertex in graph: RestChordInter{#2163 REMOVED(0.602/0.602) stf:3}
audiveris-converter  | java.lang.IllegalArgumentException: no such vertex in graph: RestChordInter{#2163 REMOVED(0.602/0.602) stf:3}
audiveris-converter  | 	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)
audiveris-converter  | 	at org.jgrapht.graph.AbstractBaseGraph.edgesOf(AbstractBaseGraph.java:444)
audiveris-converter  | 	at org.jgrapht.graph.GraphDelegator.edgesOf(GraphDelegator.java:233)
audiveris-converter  | 	at org.audiveris.omr.sig.SIGraph.getRelations(SIGraph.java:645)
audiveris-converter  | 	at org.audiveris.omr.sig.inter.AbstractChordInter.getTupletFactor(AbstractChordInter.java:1002)
audiveris-converter  | 	at org.audiveris.omr.sig.inter.AbstractChordInter.getDuration(AbstractChordInter.java:483)
....
```

Few lines after:

```
audiveris-converter  | WARN  [zizi]                     Voice 260  | Error in class org.audiveris.omr.sheet.rhythm.Voice afterReload() java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sig.inter.AbstractChordInter.justAssignVoice(org.audiveris.omr.sheet.rhythm.Voice)" because "info.chord" is null
audiveris-converter  | java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sig.inter.AbstractChordInter.justAssignVoice(org.audiveris.omr.sheet.rhythm.Voice)" because "info.chord" is null
audiveris-converter  | 	at org.audiveris.omr.sheet.rhythm.Voice.afterReload(Voice.java:252)
audiveris-converter  | 	at org.audiveris.omr.sheet.rhythm.Measure.afterReload(Measure.java:431)
audiveris-converter  | 	at org.audiveris.omr.sheet.Part.afterReload(Part.java:290)
...
```

I used the following docker image to run it: weidi/audiveris-docker#5
Apart from https://github.com/Audiveris/audiveris/issues/547, other examples run fine.

**Comment by hbitteur** [comment]
Fixed by commit 904cf29aa47b65b80bc4801fbe0dfb2c1070f50a in development branch
