### ISSUE TITLE
NPE during transcribing with newest dev version

### ISSUE THREAD

**Issue by aschoerk** [Audiveris/audiveris#583]
Hello, 
I am encountering the errors below when trying to transcribe the attached sheet.

[042.pdf](https://github.com/Audiveris/audiveris/files/8968879/042.pdf)

WARN  [2-V.aPsalm-komplett-31-43#12]            LedgersBuilder 229  | Error retrieving ledgers. java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sheet.Part.isMerged()" because "part" is null
java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sheet.Part.isMerged()" because "part" is null
	at org.audiveris.omr.sheet.ledger.LedgersBuilder.filterLedgers(LedgersBuilder.java:321)
	at org.audiveris.omr.sheet.ledger.LedgersBuilder.lambda$buildLedgers$1(LedgersBuilder.java:223)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.audiveris.omr.sheet.ledger.LedgersBuilder.buildLedgers(LedgersBuilder.java:223)
	at org.audiveris.omr.sheet.ledger.LedgersStep.doSystem(LedgersStep.java:107)
	at org.audiveris.omr.sheet.ledger.LedgersStep.doSystem(LedgersStep.java:45)
	at org.audiveris.omr.step.AbstractSystemStep.lambda$doitPerSystem$0(AbstractSystemStep.java:191)
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:211)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:104)
	at org.audiveris.omr.step.OmrStep.doit(OmrStep.java:185)
	at org.audiveris.omr.sheet.SheetStub.lambda$doOneStep$4(SheetStub.java:1331)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
WARN  [2-V.aPsalm-komplett-31-43#12]            LedgersBuilder 229  | Error retrieving ledgers. java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sheet.Part.isMerged()" because "part" is null
java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.sheet.Part.isMerged()" because "part" is null
	at org.audiveris.omr.sheet.ledger.LedgersBuilder.filterLedgers(LedgersBuilder.java:321)
	at org.audiveris.omr.sheet.ledger.LedgersBuilder.lambda$buildLedgers$1(LedgersBuilder.java:223)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.audiveris.omr.sheet.ledger.LedgersBuilder.buildLedgers(LedgersBuilder.java:223)
	at org.audiveris.omr.sheet.ledger.LedgersStep.doSystem(LedgersStep.java:107)
	at org.audiveris.omr.sheet.ledger.LedgersStep.doSystem(LedgersStep.java:45)
	at org.audiveris.omr.step.AbstractSystemStep.lambda$doitPerSystem$0(AbstractSystemStep.java:191)
	at org.audiveris.omr.step.AbstractSystemStep.doitPerSystem(AbstractSystemStep.java:211)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:104)
	at org.audiveris.omr.step.OmrStep.doit(OmrStep.java:185)
	at org.audiveris.omr.sheet.SheetStub.lambda$doOneStep$4(SheetStub.java:1331)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
WARN  [2-V.aPsalm-komplett-31-43#12]                 SheetStub 1048 | Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: Population is empty
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Population is empty
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1346)
	at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:1032)
	at org.audiveris.omr.sheet.SheetStub.transcribe(SheetStub.java:1239)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeSheetTask.doInBackground(BookActions.java:2744)
	at org.audiveris.omr.sheet.ui.BookActions$TranscribeSheetTask.doInBackground(BookActions.java:2727)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Population is empty
	at org.audiveris.omr.math.Population.getMeanValue(Population.java:112)
	at org.audiveris.omr.sheet.ledger.LedgersPostAnalysis.filter(LedgersPostAnalysis.java:193)
	at org.audiveris.omr.sheet.ledger.LedgersPostAnalysis.process(LedgersPostAnalysis.java:109)
	at org.audiveris.omr.sheet.ledger.LedgersStep.doEpilog(LedgersStep.java:92)
	at org.audiveris.omr.sheet.ledger.LedgersStep.doEpilog(LedgersStep.java:45)
	at org.audiveris.omr.step.AbstractSystemStep.doit(AbstractSystemStep.java:107)
	at org.audiveris.omr.step.OmrStep.doit(OmrStep.java:185)
	at org.audiveris.omr.sheet.SheetStub.lambda$doOneStep$4(SheetStub.java:1331)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 common frames omitted

**Comment by hbitteur** [comment]
No news on this issue.
Should we close it?
