### ISSUE TITLE
Error on loading pdf

### ISSUE THREAD

**Issue by RensBloom** [Audiveris/audiveris#592]
When trying to load [IMSLP 19937](http://vmirror.imslp.org/files/imglnks/usimg/e/ee/IMSLP19937-PMLP46644-Dvorak_Witch_Perc.pdf) I get an error message `[IMSLP19937#1] Error in performing [LOAD, BINARY] java.util.concurrent.ExecutionException: de.intarsys.pdf.content.CSError: Image can't be rendered (java.util.NoSuchElementException)`

```INFO  []                      Main 401  | Environment:
- Audiveris:    5.2.5:09bbb8236
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 11.0.2+9, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []                       CLI 269  | CLI args: []
INFO  []             AliasPatterns 131  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                   MainGui 415  | Audiveris version 5.2.5
INFO  []                   MainGui 416  |
LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No C:\Users\rensb\AppData\Roaming\AudiverisLtd\audiveris\config\logback.xml, skipped.
LogUtil. Configuration found jar:file:/C:/Program%20Files/Audiveris/lib/audiveris.jar!/res/logback.xml
LogUtil. Logging to C:\Users\rensb\AppData\Roaming\AudiverisLtd\audiveris\log\20221114T103337.log

INFO  []            PluginsManager 239  | No C:\Users\rensb\AppData\Roaming\AudiverisLtd\audiveris\config\plugins.xml file found
INFO  []                  Versions 392  | Versions. Poll frequency: Weekly, next poll on: 21-Nov-2022
INFO  []           BasicClassifier 366  | Classifier loaded XML norms.
INFO  []        AbstractClassifier 352  | Classifier data loaded from default uri jar:file:/C:/Program%20Files/Audiveris/lib/audiveris.jar!/res/basic-classifier.zip
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jgoodies.common.internal.RenderingUtils (file:/C:/Program%20Files/Audiveris/lib/jgoodies-common-1.8.1.jar) to method sun.swing.SwingUtilities2.drawStringUnderlineCharAt(javax.swing.JComponent,java.awt.Graphics,java.lang.String,int,int,int)
WARNING: Please consider reporting this to the maintainers of com.jgoodies.common.internal.RenderingUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  []               BookManager 560  | Found alias: IMSLP19937 for IMSLP19937-PMLP46644-Dvorak_Witch_Perc
INFO  [IMSLP19937]                      Book 485  | 6 sheets in D:\Rens\Documents\bladmuziek\ZSO\IMSLP19937-PMLP46644-Dvorak_Witch_Perc.pdf
WARN  [IMSLP19937#1]                 SheetStub 1048 | Error in performing [LOAD, BINARY] java.util.concurrent.ExecutionException: de.intarsys.pdf.content.CSError: Image can't be rendered (java.util.NoSuchElementException)
java.util.concurrent.ExecutionException: de.intarsys.pdf.content.CSError: Image can't be rendered (java.util.NoSuchElementException)
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:1346)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:1032)
        at org.audiveris.omr.sheet.ui.StubsController.checkStubStatus(StubsController.java:839)
        at org.audiveris.omr.sheet.ui.StubsController.lambda$display$3(StubsController.java:606)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: de.intarsys.pdf.content.CSError: Image can't be rendered (java.util.NoSuchElementException)
        at de.intarsys.pdf.platform.cwt.rendering.CSPlatformDevice.doImage(CSPlatformDevice.java:348)
        at de.intarsys.pdf.content.CSDeviceAdapter.doXObject(CSDeviceAdapter.java:212)
        at de.intarsys.pdf.content.CSDeviceBasedInterpreter.render_Do(CSDeviceBasedInterpreter.java:332)
        at de.intarsys.pdf.content.CSInterpreter.process(CSInterpreter.java:449)
        at de.intarsys.pdf.content.CSInterpreter.process(CSInterpreter.java:206)
        at de.intarsys.pdf.content.CSDeviceBasedInterpreter.process(CSDeviceBasedInterpreter.java:195)
        at org.audiveris.omr.image.ImageLoading$JPodLoader.getImage(ImageLoading.java:468)
        at org.audiveris.omr.sheet.Book.loadSheetImage(Book.java:1557)
        at org.audiveris.omr.step.LoadStep.doit(LoadStep.java:71)
        at org.audiveris.omr.step.OmrStep.doit(OmrStep.java:185)
        at org.audiveris.omr.sheet.SheetStub.lambda$doOneStep$4(SheetStub.java:1331)
        ... 4 common frames omitted
Caused by: de.intarsys.cwt.image.ImageException: java.util.NoSuchElementException
        at de.intarsys.pdf.platform.cwt.image.awt.ImageConverterPdf2Awt.createBufferedImage(ImageConverterPdf2Awt.java:88)
        at de.intarsys.pdf.platform.cwt.image.awt.ImageConverterPdf2Awt.createBufferedImage(ImageConverterPdf2Awt.java:334)
        at de.intarsys.pdf.platform.cwt.image.awt.ImageConverterPdf2Awt.getBufferedImage(ImageConverterPdf2Awt.java:394)        at de.intarsys.pdf.platform.cwt.adapter.awt.AwtGraphicsEnvironmentAdapter.createImage(AwtGraphicsEnvironmentAdapter.java:72)
        at de.intarsys.pdf.platform.cwt.adapter.awt.AwtGraphicsEnvironmentAdapter.drawImage(AwtGraphicsEnvironmentAdapter.java:173)
        at de.intarsys.pdf.platform.cwt.image.CwtPlatformImage.drawFromGraphicsContext(CwtPlatformImage.java:49)
        at de.intarsys.cwt.awt.environment.CwtAwtGraphicsContext.drawImage(CwtAwtGraphicsContext.java:102)
        at de.intarsys.pdf.platform.cwt.image.CwtPlatformImage.doImage(CwtPlatformImage.java:41)
        at de.intarsys.pdf.platform.cwt.rendering.CSPlatformDevice.doImage(CSPlatformDevice.java:341)
        ... 14 common frames omitted
Caused by: java.util.NoSuchElementException: null
        at java.desktop/javax.imageio.spi.FilterIterator.next(ServiceRegistry.java:891)
        at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:531)
        at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
        at de.intarsys.pdf.platform.cwt.image.awt.ImageConverterPdf2Awt.createRasterFromAnyJPEG(ImageConverterPdf2Awt.java:195)
        at de.intarsys.pdf.platform.cwt.image.awt.ImageConverterPdf2Awt.createRasterFromJPEG(ImageConverterPdf2Awt.java:298)
        at de.intarsys.pdf.platform.cwt.image.awt.ImageConverterPdf2Awt.createRaster(ImageConverterPdf2Awt.java:172)
        at de.intarsys.pdf.platform.cwt.image.awt.ImageConverterPdf2Awt.createBufferedImage(ImageConverterPdf2Awt.java:83)
        ... 22 common frames omitted```

**Comment by RensBloom** [comment]
I tried some other PDF files from the same piece and uploader, but didn't encounter this problem.

**Comment by hbitteur** [comment]
No news on this issue.
Should we close it?

**Comment by PeterGreth** [comment]
Since I've recently opened a PR replacing the jPod Renderer with Apache PDFBox (#666 ), I tried the Pdf with the new renderer and... it also failed. Luckily the error message was better: The Pdf contains "JPEG 2000 (JPX)" images that cannot be handled by the renderer.

Fixing this in the renderer seems to be a greater act, so I tried to fix the Pdf. I simply converted it to pngs using https://pdf2png.com/ and then converted it back to pdfs using the same site:

[IMSLP19937-PMLP46644-Dvorak_Witch_Perc_without_JPEG2000.pdf](https://github.com/Audiveris/audiveris/files/12347064/IMSLP19937-PMLP46644-Dvorak_Witch_Perc_without_JPEG2000.pdf)

It now works both in the PDFBox renderer and the jPod Renderer 👍

**Comment by jenia0jenia** [comment]
I had the same problem with my PDF and @PeterGreth's post helps me.
File with error - 
[bach.pdf](https://github.com/Audiveris/audiveris/files/13248103/bach.pdf)
