### ISSUE TITLE
Long building time on Mac OS (Maybe?)

### ISSUE THREAD

**Issue by KaiVinter** [Audiveris/audiveris#627]
Hello!
This is the first time I build a piece of software myself, so it's probably something I'm not used to. But for now the build has stopped at 83% and Audiveris shows 89/512 MB in the 'Used Memory / Global Memory' box, and it seems to be increasing a little progressively. Is this how it's supposed to work? Or am I missing something?

It also says 'Unable to setup Mac OS X GUI integration'. Is this an error or just default behavior?

![Screen Shot 2023-03-01 at 6 11 15 PM](https://user-images.githubusercontent.com/88064903/222315861-a2a6c40e-de0e-4172-a85d-4a057b827c12.png)

**Comment by KaiVinter** [comment]
This is the build log (is that the name?)

```
❯ ./gradlew run
Downloading https://services.gradle.org/distributions/gradle-7.3-all.zip
.......................................................................................................................................................

Welcome to Gradle 7.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
targetOS=macosx-x86_64

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :run
INFO  []                      Main 402  | Environment:
- Audiveris:    5.3-beta:3ab254b76
- OS:           Mac OS X 12.6.1
- Architecture: x86_64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
- OCR Engine:   Tesseract OCR, version 4.1.1
INFO  []                       CLI 282  | CLI args: []
INFO  []             AliasPatterns 134  | Alias patterns: [(IMSLP[0-9]*)-.*]
Mac OS X Adapter could not talk to EAWT:
java.lang.IllegalAccessException: class org.jdesktop.application.utils.OSXAdapter cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @192d3247
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.jdesktop.application.utils.OSXAdapter.setHandler(OSXAdapter.java:140)
        at org.jdesktop.application.utils.OSXAdapter.setQuitHandler(OSXAdapter.java:74)
        at org.jdesktop.application.Application.create(Application.java:257)
        at org.jdesktop.application.Application$1.run(Application.java:185)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO  []                   MainGui 570  | Audiveris version 5.3-beta
INFO  []                   MainGui 571  |
LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No /Users/joshuamastachi/Library/Application Support/AudiverisLtd/audiveris/logback.xml, skipped.
LogUtil. Configuration found file:///Users/joshuamastachi/audiveris/res/logback.xml
LogUtil. Logging to /Users/joshuamastachi/Library/AudiverisLtd/audiveris/log/20230301T174154.log

INFO  []            PluginsManager 210  | No /Users/joshuamastachi/Library/Application Support/AudiverisLtd/audiveris/plugins.xml file found
INFO  []           BasicClassifier 277  | Classifier loaded XML norms.
INFO  []        AbstractClassifier 396  | Classifier data loaded from default uri file:///Users/joshuamastachi/audiveris/res/basic-classifier.zip
WARN  []            MacApplication 235  | Unable to setup Mac OS X GUI integration
java.lang.IllegalAccessException: class org.audiveris.omr.ui.MacApplication cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @192d3247
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at org.audiveris.omr.ui.MacApplication.setupMacMenus(MacApplication.java:196)
        at org.audiveris.omr.ui.MainGui.defineMenus(MainGui.java:300)
        at org.audiveris.omr.ui.MainGui.startup(MainGui.java:586)
        at org.jdesktop.application.Application$1.run(Application.java:187)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO  []                  Versions 301  | Versions. Poll frequency: Weekly, next poll on: 08-Jan-2000
INFO  []                  Versions 397  | Software version is up-to-date
INFO  []                GuiActions 331  |
----- Occupied memory is 20,164,488 bytes -----

<==========---> 83% EXECUTING [55m 41s]
> IDLE
> IDLE
> :run
> IDLE

```

**Comment by maximumspatium** [comment]
The above log looks okay to me. You're getting a couple of errors during the `Run` task because Mac OS specific UI part in Audiveris still uses a deprecated functionality. Removing calls to the deprecated Mac OS API is on my TODO list - I didn't get around it yet.
Don't worry about Mac OS integration errors - it's safe to ignore them. Audiveris should be fully operational.
