### ISSUE TITLE
Reduction timeout

### ISSUE THREAD

**Issue by APridgeon** [Audiveris/audiveris#663]
I have been trying to scan a score. Most pages are scanned ok, but for some reason this page (pdf attached) induces a timeout on the reduction step. I imagine it might be the overlapping elements between Tba and bat. Is there anyway to fix this? 

I'm using the most recent version from the development branch on a mac 

The terminal outputs the following upon the error:

INFO  []                      Book 601  | 1 sheet in /Users/ashleypridgeon/Desktop/ErrorPage.pdf
INFO  [ErrorPage]                      Book 1845 | Loaded image 1 2479x3508 from /Users/ashleypridgeon/Desktop/ErrorPage.pdf
INFO  [ErrorPage]              ScaleBuilder 234  | Beam  guessed height:  8 -- 0.50 of 17 interline
INFO  [ErrorPage]              ScaleBuilder 257  | Beam measured height:  9 -- 0.33 of [5..17] range at 175% of needed quorum
INFO  [ErrorPage]                 ScaleStep 65   | Scale{ interline(16,17,17) line(1,1,2) beam(9)}
INFO  [ErrorPage]            LinesRetriever 1490 | Global slope: 0.00000
INFO  [ErrorPage]         ClustersRetriever 334  | Retrieved line clusters: 22 of sizes [5] with interline(16,17,17)
INFO  [ErrorPage]                 PeakGraph 310  | Systems: #1[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
INFO  [ErrorPage]             BarsRetriever 1296 | System#1
INFO  [ErrorPage]             BarsRetriever 1299 |    PartGroup{bracket number:1 barline:true staves:1-8}
INFO  [ErrorPage]             BarsRetriever 1299 |    PartGroup{bracket number:1 barline:true staves:9-10}
INFO  [ErrorPage]             BarsRetriever 1299 |    PartGroup{bracket number:1 barline:true staves:12-14}
INFO  [ErrorPage]             BarsRetriever 1299 |    PartGroup{bracket number:1 barline:true staves:15-16}
INFO  [ErrorPage]             BarsRetriever 1299 |    PartGroup{bracket number:1 barline:true staves:17-21}
INFO  [ErrorPage]             SystemManager 736  | 22 parts along 1 system
INFO  [ErrorPage]                      Book 584  | Created scores: [{Score 1}]
INFO  [ErrorPage]                 ImageUtil 204  | Discarding alpha band ...
INFO  [ErrorPage]                 ImageUtil 122  | Converting max RGB to gray
INFO  [ErrorPage]             StemSeedsStep 86   | stem(1 max:2)
INFO  [ErrorPage]                   DrumSet 175  | Loading drum set entries from file:///Users/ashleypridgeon/opt/audiveris/res/drum-set.xml
INFO  [ErrorPage]                   DrumSet 110  | 
INFO  [ErrorPage]                   DrumSet 111  | Resulting Drum Set:
INFO  [ErrorPage]                   DrumSet 115  | 
INFO  [ErrorPage]                   DrumSet 116  |   line-count: 1
INFO  [ErrorPage]                   DrumSet 115  | 
INFO  [ErrorPage]                   DrumSet 116  |   line-count: 5
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: -8
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Splash_Cymbal
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Chinese_Cymbal
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: -7
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Crash_Cymbal_2
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Crash_Cymbal_2
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: -6
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Crash_Cymbal_1
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Crash_Cymbal_1
INFO  [ErrorPage]                   DrumSet 127  |       motif: diamond  sound: Crash_Cymbal_1
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: -5
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sign: PLAYING_OPEN      sound: Open_Hi_Hat
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Open_Hi_Hat
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sign: PLAYING_CLOSED    sound: Closed_Hi_Hat
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Closed_Hi_Hat
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: -4
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: High_Tom
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Ride_Cymbal_1
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Ride_Cymbal_1
INFO  [ErrorPage]                   DrumSet 127  |       motif: diamond  sound: Ride_Bell
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: -3
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: Hi_Mid_Tom
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Open_Hi_Hat
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Open_Hi_Hat
INFO  [ErrorPage]                   DrumSet 127  |       motif: triangle sound: Cowbell
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: -2
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: Low_Mid_Tom
INFO  [ErrorPage]                   DrumSet 127  |       motif: triangle sound: Cowbell
INFO  [ErrorPage]                   DrumSet 127  |       motif: diamond  sound: Tambourine
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Ride_Cymbal_2
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Ride_Cymbal_2
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: -1
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: Acoustic_Snare
INFO  [ErrorPage]                   DrumSet 127  |       motif: small    sound: Acoustic_Snare
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Side_Stick
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Side_Stick
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: 0
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: Low_Tom
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: 1
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: High_Floor_Tom
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: 2
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: Low_Floor_Tom
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Low_Conga
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Low_Conga
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: 3
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: Bass_Drum_1
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: 4
INFO  [ErrorPage]                   DrumSet 127  |       motif: oval     sound: Acoustic_Bass_Drum
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Open_Hi_Conga
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Open_Hi_Conga
INFO  [ErrorPage]                   DrumSet 120  |     pitch-position: 5
INFO  [ErrorPage]                   DrumSet 127  |       motif: cross    sound: Pedal_Hi_Hat
INFO  [ErrorPage]                   DrumSet 127  |       motif: circle   sound: Open_Hi_Hat
INFO  [ErrorPage]                   DrumSet 137  | 
INFO  [ErrorPage]             HeadSeedTally 235  | Scale information: HeadSeeds{NOTEHEAD_VOID[R:0.1] NOTEHEAD_BLACK[L:-0.2,R:-0.1]}
WARN  [ErrorPage]                 SheetStub 578  | Timeout 120 seconds for step REDUCTION
java.util.concurrent.TimeoutException: null
        at [java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)]
[ErrorPage.pdf](https://github.com/Audiveris/audiveris/files/12280297/ErrorPage.pdf)

        at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:570)
        at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:1358)
        at org.audiveris.omr.step.ui.StepMenu$StepAction$1.doInBackground(StepMenu.java:225)
        at org.audiveris.omr.step.ui.StepMenu$StepAction$1.doInBackground(StepMenu.java:174)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
INFO  [ErrorPage]                  StepMenu 231  | ProcessingCancellationException detected

**Comment by PeterGreth** [comment]
Just had a quick look at this. Audiveris runs into an endless loop in `SigReducer::checkLedgers`:

- Audivers thinks that the ledgers above the 1st clarinet staff (`3`) belong to the Eb clarinet staff (`2`) above
![image](https://github.com/Audiveris/audiveris/assets/10603720/6aac5eb0-7f57-4f3f-bb8f-3c20a2ccc18b)

- in `SigReducer::checkLedgers` it iterates over the staves: For each staff, it removes ledgers that dont have a head or another ledger following. Due to the point above, in staff 2, it also iterates over the ledgers that actually belong to staff 3.
- Problem: In this method, when deleting such a ledger for staff 2, the ledger is only removed from its containing staff (which Audiveris correctly detects as staff 3). Staff 2 still keeps the ledger in its ledger map.

I think there are several solutions to this problem. I don't have deep enough knowledge of Audiveris to decide for one, but @hbitteur does :) 

1. The ledgers of staff 3 should never have never been assigned to staff 2 -> Somehow prevent this?
2. When removing such a ledger, remove it from all staves Audiveris _thinks_ it belongs to (in this case staves 2 and 3)
3. Accept this case and just prevent it from causing an endless loop -> Set [modified = true](https://github.com/Audiveris/audiveris/blob/master/src/main/org/audiveris/omr/sig/SigReducer.java#L934) only if the ledger has not already been removed

**Comment by APridgeon** [comment]
@PeterGreth thank you very much! These might be some novice questions (sorry!) but -

1) how did you figure out the sigreducer loop (the log didn't mention it)?

2) Also how can I correct that in audiveris (is it right click->inters->dump the rels mentioning the wrong stave)?

**Comment by PeterGreth** [comment]
1. I have the code of Audiveris checked out locally and started Audiveris in my IDE. With a good IDE (I prefer IntelliJ, I have heard that @hbitteur uses NetBeans), you can debug applications. You can then set breakpoints and step through the program execution line by line. I just did that until I found the method that runs for a long time. Then I looked at the values of the staves until I understood why the loop never terminated.
2. I don't know yet how to correct something in Audiveris, sorry :D

**Comment by hbitteur** [comment]
The root cause is that staves are not enough vertically separated in the input image.
This defeats the current ledgers algorithm which assumes that there is enough vertical space between the last ledger of a staff and the next staff.

Right now, the 3 ledgers appear both in staff 2 ledgerMap  and in staff 3 ledgerMap.
This is something a modified version of current algorithm could detect!
If we could decide which staff is the legitimate owner, then cleaning up the other staff would be  rather easy.

But in the case at hand, how could we convince the algorithm that the first ledger below staff 2 belongs in fact to staff 3?
As a human reader, we can relie on the fact that the somehow related stem goes down into staff 3.
But, what if we had no stem, but stem-less whole heads?
Should we count the number of ledgers between staff line and note head, and give preference to the staff for which the number of interleaved ledgers is higher? <== This is my preferred criteria, what do you think?

**Comment by APridgeon** [comment]
Ah @PeterGreth thank you very much! 

And @hbitteur thanks for your explanation. I think you're criteria sounds like a decent way of determining the staff.

**Comment by hbitteur** [comment]
Bug fixed today in commit 1d8106343791ddd40aaddac90c5e53356dfd1377 on "development" branch.
Please pull.
