### ISSUE TITLE
Reduction timeout

### ISSUE THREAD

**Issue by jenia0jenia** [Audiveris/audiveris#695]
Hi! Many thanks to the developers! Mostly I get the recognition correct, but I'm having an error with this one

```
2023-11-08 13:27:52,950 INFO [n0001786]                 Book.java:601  | 3 sheets in /home/cher/projects/nota/pdf/n0001786.pdf
2023-11-08 13:27:53,105 INFO []                 Book.java:2515 | Stored /book.xml
2023-11-08 13:27:53,105 INFO []                 Book.java:2476 | Book stored as /home/cher/projects/nota/omr/n0001786/n0001786.omr
2023-11-08 13:27:53,128 INFO []                 Book.java:1963 | Book reaching PAGE on sheets:[#1#2#3]
2023-11-08 13:27:53,130 INFO [n0001786#1]       StepMonitoring.java:98   | LOAD
2023-11-08 13:27:53,336 INFO [n0001786#1]                 Book.java:1845 | Loaded image 1 2800x3602 from /home/cher/projects/nota/pdf/n0001786.pdf
2023-11-08 13:27:53,339 INFO [n0001786#1]       StepMonitoring.java:98   | BINARY
2023-11-08 13:27:54,021 INFO [n0001786#1]       StepMonitoring.java:98   | SCALE
2023-11-08 13:27:54,029 INFO [n0001786#1]                 Book.java:584  | Created scores: []
2023-11-08 13:27:54,030 INFO [n0001786#1]            SheetStub.java:1252 | Sheet n0001786#1 flagged as invalid.
2023-11-08 13:27:54,030 INFO [n0001786#1]            SheetStub.java:1372 | StepException cause detected in [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE]
2023-11-08 13:27:54,031 INFO [n0001786#1]                 Book.java:2535 | Book{n0001786} storing
2023-11-08 13:27:54,051 INFO [n0001786#1]                 Book.java:2515 | Stored /book.xml
2023-11-08 13:27:54,181 INFO [n0001786#1]           DataHolder.java:348  | Stored /sheet#1/BINARY.png
2023-11-08 13:27:54,392 INFO [n0001786#1]                Sheet.java:1529 | Stored /sheet#1/sheet#1.xml
2023-11-08 13:27:54,392 INFO [n0001786#1]                 Book.java:2476 | Book stored as /home/cher/projects/nota/omr/n0001786/n0001786.omr
2023-11-08 13:27:54,394 INFO [n0001786#1]            SheetStub.java:1605 | Disposed sheet#1
2023-11-08 13:27:54,424 INFO [n0001786#1]                 Book.java:2035 | End of Stub#1 memory: 9,789,976
2023-11-08 13:27:54,425 INFO [n0001786#2]       StepMonitoring.java:98   | LOAD
2023-11-08 13:27:54,585 INFO [n0001786#2]                 Book.java:1845 | Loaded image 2 2800x3602 from /home/cher/projects/nota/pdf/n0001786.pdf
2023-11-08 13:27:54,586 INFO [n0001786#2]       StepMonitoring.java:98   | BINARY
2023-11-08 13:27:55,288 INFO [n0001786#2]       StepMonitoring.java:98   | SCALE
2023-11-08 13:27:55,310 INFO [n0001786#2]         ScaleBuilder.java:234  | Beam  guessed height: 10 -- 0.50 of 20 interline
2023-11-08 13:27:55,313 INFO [n0001786#2]         ScaleBuilder.java:257  | Beam measured height: 15 -- 0.58 of [8..20] range at 184% of needed quorum
2023-11-08 13:27:55,313 INFO [n0001786#2]            ScaleStep.java:65   | Scale{ interline(19,20,22) line(3,6,8) beam(15)}
2023-11-08 13:27:55,314 INFO [n0001786#2]       StepMonitoring.java:98   | GRID
2023-11-08 13:27:57,616 INFO [n0001786#2]       LinesRetriever.java:1490 | Global slope: -0.00283
2023-11-08 13:27:57,683 INFO [n0001786#2]    ClustersRetriever.java:334  | Retrieved line clusters: 12 of sizes [5] with interline(19,20,22)
2023-11-08 13:27:58,386 INFO [n0001786#2]            PeakGraph.java:310  | Systems: #1[1, 2, 3] #2[4, 5, 6] #3[7, 8, 9] #4[10, 11, 12]
2023-11-08 13:28:00,067 INFO [n0001786#2]        SystemManager.java:149  | Indentation detected for system#1
2023-11-08 13:28:00,068 INFO [n0001786#2]        SystemManager.java:736  | 2 parts along 4 systems
2023-11-08 13:28:00,069 INFO [n0001786#2]                 Book.java:584  | Created scores: [{Score 1}]
2023-11-08 13:28:00,070 INFO [n0001786#2]       StepMonitoring.java:98   | HEADERS
2023-11-08 13:28:00,260 INFO [n0001786#2]      BasicClassifier.java:277  | Classifier loaded XML norms.
2023-11-08 13:28:00,266 INFO [n0001786#2]   AbstractClassifier.java:396  | Classifier data loaded from default uri file:///home/cher/projects/audiveris/res/basic-classifier.zip
2023-11-08 13:28:00,870 INFO [n0001786#2]       StepMonitoring.java:98   | STEM_SEEDS
2023-11-08 13:28:00,967 INFO [n0001786#2]            ImageUtil.java:204  | Discarding alpha band ...
2023-11-08 13:28:01,184 INFO [n0001786#2]            ImageUtil.java:122  | Converting max RGB to gray
2023-11-08 13:28:01,460 INFO [n0001786#2]        StemSeedsStep.java:86   | stem(5 max:7)
2023-11-08 13:28:01,543 INFO [n0001786#2]       StepMonitoring.java:98   | BEAMS
2023-11-08 13:28:07,720 INFO [n0001786#2]       StepMonitoring.java:98   | LEDGERS
2023-11-08 13:28:08,392 INFO [n0001786#2]       StepMonitoring.java:98   | HEADS
2023-11-08 13:28:14,009 INFO [n0001786#2]        HeadSeedTally.java:235  | Scale information: HeadSeeds{NOTEHEAD_VOID[R:-1.0] NOTEHEAD_BLACK[L:-1.5,R:-0.7]}
2023-11-08 13:28:14,010 INFO [n0001786#2]       StepMonitoring.java:98   | STEMS
2023-11-08 13:28:15,192 INFO [n0001786#2]       StepMonitoring.java:98   | REDUCTION
2023-11-08 13:28:15,284 INFO [n0001786#2]        ReductionStep.java:93   | Stems free length median value: 73 pixels, 3.7 interlines
2023-11-08 13:28:15,284 INFO [n0001786#2]       StepMonitoring.java:98   | CUE_BEAMS
2023-11-08 13:28:15,285 INFO [n0001786#2]         CueBeamsStep.java:81   | Step CUE_BEAMS is skipped because small heads switch is off
2023-11-08 13:28:15,285 INFO [n0001786#2]       StepMonitoring.java:98   | TEXTS
2023-11-08 13:28:15,286 WARN [n0001786#2]            TextsStep.java:97   | TEXTS step: No OCR is available!
2023-11-08 13:28:15,292 INFO [n0001786#2]       StepMonitoring.java:98   | MEASURES
2023-11-08 13:28:15,298 INFO [n0001786#2]                 Page.java:308  | 8 raw measures: [2 in system#1, 2 in system#2, 2 in system#3, 2 in system#4]
2023-11-08 13:28:15,298 INFO [n0001786#2]       StepMonitoring.java:98   | CHORDS
2023-11-08 13:28:15,315 INFO [n0001786#2]       StepMonitoring.java:98   | CURVES
2023-11-08 13:28:16,661 INFO [n0001786#2]         SlursBuilder.java:240  | Slurs: 2
2023-11-08 13:28:16,675 INFO [n0001786#2]      SegmentsBuilder.java:155  | Segments: 4
2023-11-08 13:28:16,678 INFO [n0001786#2]       StepMonitoring.java:98   | SYMBOLS
2023-11-08 13:28:19,812 INFO [n0001786#2]       StepMonitoring.java:98   | LINKS
2023-11-08 13:28:19,841 INFO [n0001786#2]        SymbolsLinker.java:424  | No chord above PedalInter#7300{(0.186) PEDAL_MARK}
2023-11-08 13:28:19,841 INFO [n0001786#2]        SymbolsLinker.java:424  | No chord above PedalInter#7620{(0.190) PEDAL_MARK}
2023-11-08 13:28:19,842 INFO [n0001786#2]        SymbolsLinker.java:424  | No chord above PedalInter#7634{(0.126) PEDAL_UP_MARK}
2023-11-08 13:28:19,842 INFO [n0001786#2]        SymbolsLinker.java:424  | No chord above PedalInter#7668{(0.192) PEDAL_MARK}
2023-11-08 13:28:19,847 INFO [n0001786#2]       StepMonitoring.java:98   | RHYTHMS
2023-11-08 13:28:19,862 INFO [n0001786#2]        MeasureRhythm.java:985  | Measure{#2P2} No timeOffset for HeadChordInter#4567{(0.948/0.948) stf:2 slot#2 dur:1/8}
2023-11-08 13:28:19,863 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#2P2} No timeOffset for HeadChordInter#4568{(0.956/0.956) stf:2 slot#3 dur:1/8}
2023-11-08 13:28:19,863 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#2P2} No timeOffset for HeadChordInter#4568{(0.956/0.956) stf:2 slot#3 dur:1/8}
2023-11-08 13:28:19,864 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#2P2} No timeOffset for RestChordInter#6796{(0.737/0.737) stf:2 slot#4 dur:1/8}
2023-11-08 13:28:19,864 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#2P2} No timeOffset for HeadChordInter#4570{(0.957/0.957) stf:2 slot#6 dur:1/8}
2023-11-08 13:28:19,867 INFO [n0001786#2]        MeasureRhythm.java:985  | Measure{#3P1} No timeOffset for HeadChordInter#4579{(0.949/0.949) stf:4 slot#5 dur:1/8}
2023-11-08 13:28:19,868 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#3P1} No timeOffset for HeadChordInter#4579{(0.949/0.949) stf:4 slot#5 dur:1/8}
2023-11-08 13:28:19,869 INFO [n0001786#2]                Voice.java:256  | Measure{#3P1} Voice{#1 excess:1/8} too long
2023-11-08 13:28:19,872 INFO [n0001786#2]        MeasureRhythm.java:985  | Measure{#4P2} No timeOffset for HeadChordInter#4586{(0.955/0.955) stf:5 slot#2 dur:1/8}
2023-11-08 13:28:19,872 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#4P2} No timeOffset for HeadChordInter#4587{(0.958/0.958) stf:5 slot#3 dur:1/8}
2023-11-08 13:28:19,873 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#4P2} No timeOffset for HeadChordInter#4587{(0.958/0.958) stf:5 slot#3 dur:1/8}
2023-11-08 13:28:19,873 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#4P2} No timeOffset for HeadChordInter#4587{(0.958/0.958) stf:5 slot#3 dur:1/8}
2023-11-08 13:28:19,880 INFO [n0001786#2]        MeasureRhythm.java:985  | Measure{#7P1} No timeOffset for HeadChordInter#4622{(0.877/0.877) stf:10 slot#6 dur:1/8}
2023-11-08 13:28:19,881 INFO [n0001786#2]                Voice.java:256  | Measure{#7P1} Voice{#1 excess:1/8} too long
2023-11-08 13:28:19,882 INFO [n0001786#2]        MeasureRhythm.java:985  | Measure{#7P2} No timeOffset for HeadChordInter#4624{(0.964/0.964) stf:11 slot#2 dur:1/8}
2023-11-08 13:28:19,883 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#7P2} No timeOffset for HeadChordInter#4625{(0.960/0.960) stf:11 slot#3 dur:1/8}
2023-11-08 13:28:19,883 INFO [n0001786#2]   AbstractChordInter.java:632  | Measure{#7P2} No timeOffset for HeadChordInter#4628{(0.930/0.930) stf:11 slot#6 dur:1/8}
2023-11-08 13:28:19,887 INFO [n0001786#2]                Voice.java:256  | Measure{#8P2} Voice{#1 excess:1/16} too long
2023-11-08 13:28:19,888 INFO [n0001786#2]       StepMonitoring.java:98   | PAGE
2023-11-08 13:28:19,894 INFO [n0001786#2]                Voice.java:256  | Measure{#3P1} Voice{#1 excess:1/8} too long
2023-11-08 13:28:19,895 INFO [n0001786#2]                Voice.java:256  | Measure{#7P1} Voice{#1 excess:1/8} too long
2023-11-08 13:28:19,895 INFO [n0001786#2]                Voice.java:256  | Measure{#8P2} Voice{#1 excess:1/16} too long
2023-11-08 13:28:19,896 INFO [n0001786#2]                 Book.java:2535 | Book{n0001786} storing
2023-11-08 13:28:19,989 INFO [n0001786#2]                 Book.java:2515 | Stored /book.xml
2023-11-08 13:28:20,078 INFO [n0001786#2]           DataHolder.java:348  | Stored /sheet#2/BINARY.png
2023-11-08 13:28:20,887 INFO [n0001786#2]                Sheet.java:1529 | Stored /sheet#2/sheet#2.xml
2023-11-08 13:28:20,887 INFO [n0001786#2]                 Book.java:2476 | Book stored as /home/cher/projects/nota/omr/n0001786/n0001786.omr
2023-11-08 13:28:20,895 INFO [n0001786#2]            SheetStub.java:1605 | Disposed sheet#2
2023-11-08 13:28:20,935 INFO [n0001786#2]                 Book.java:2035 | End of Stub#2 memory: 29,151,112
2023-11-08 13:28:20,935 INFO [n0001786#3]       StepMonitoring.java:98   | LOAD
2023-11-08 13:28:21,081 INFO [n0001786#3]                 Book.java:1845 | Loaded image 3 2800x3602 from /home/cher/projects/nota/pdf/n0001786.pdf
2023-11-08 13:28:21,081 INFO [n0001786#3]       StepMonitoring.java:98   | BINARY
2023-11-08 13:28:21,704 INFO [n0001786#3]       StepMonitoring.java:98   | SCALE
2023-11-08 13:28:21,733 INFO [n0001786#3]         ScaleBuilder.java:234  | Beam  guessed height: 10 -- 0.50 of 20 interline
2023-11-08 13:28:21,734 INFO [n0001786#3]         ScaleBuilder.java:257  | Beam measured height: 15 -- 0.62 of [7..20] range at 347% of needed quorum
2023-11-08 13:28:21,734 INFO [n0001786#3]            ScaleStep.java:65   | Scale{ interline(19,20,22) line(4,5,7) beam(15)}
2023-11-08 13:28:21,734 INFO [n0001786#3]       StepMonitoring.java:98   | GRID
2023-11-08 13:28:23,260 INFO [n0001786#3]       LinesRetriever.java:1490 | Global slope: 0.00606
2023-11-08 13:28:23,294 INFO [n0001786#3]    ClustersRetriever.java:334  | Retrieved line clusters: 15 of sizes [5] with interline(19,20,22)
2023-11-08 13:28:23,835 INFO [n0001786#3]            PeakGraph.java:310  | Systems: #1[1, 2, 3] #2[4, 5, 6] #3[7, 8, 9] #4[10, 11, 12] #5[13, 14, 15]
2023-11-08 13:28:23,864 WARN [n0001786#3]        BarsRetriever.java:373  | Staff#8 expected brace middle/bottom
2023-11-08 13:28:23,871 INFO [n0001786#3]        BarsRetriever.java:769  | No brace partner at level:1 for Peak{297-314 F#12070 T#2 [BRACE, BRACE_MIDDLE]}
2023-11-08 13:28:23,871 INFO [n0001786#3]        BarsRetriever.java:769  | No brace partner at level:1 for Peak{293-312 F#12071 T#3 [BRACE, BRACE_BOTTOM]}
2023-11-08 13:28:23,871 INFO [n0001786#3]        BarsRetriever.java:1296 | System#3
2023-11-08 13:28:23,872 INFO [n0001786#3]        BarsRetriever.java:1299 |    PartGroup{brace number:1 barline:false staves:7}
2023-11-08 13:28:25,093 INFO [n0001786#3]        SystemManager.java:736  | 3 parts along 5 systems
2023-11-08 13:28:25,094 INFO [n0001786#3]       StepMonitoring.java:98   | HEADERS
2023-11-08 13:28:25,520 INFO [n0001786#3]       StepMonitoring.java:98   | STEM_SEEDS
2023-11-08 13:28:25,584 INFO [n0001786#3]            ImageUtil.java:204  | Discarding alpha band ...
2023-11-08 13:28:25,792 INFO [n0001786#3]            ImageUtil.java:122  | Converting max RGB to gray
2023-11-08 13:28:25,985 INFO [n0001786#3]        StemSeedsStep.java:86   | stem(5 max:7)
2023-11-08 13:28:26,009 INFO [n0001786#3]       StepMonitoring.java:98   | BEAMS
2023-11-08 13:28:32,227 INFO [n0001786#3]       StepMonitoring.java:98   | LEDGERS
2023-11-08 13:28:32,670 INFO [n0001786#3]       StepMonitoring.java:98   | HEADS
2023-11-08 13:28:40,751 INFO [n0001786#3]        HeadSeedTally.java:235  | Scale information: HeadSeeds{NOTEHEAD_VOID[L:-2.1,R:-1.0] NOTEHEAD_BLACK[L:-1.5,R:-1.3]}
2023-11-08 13:28:40,752 INFO [n0001786#3]       StepMonitoring.java:98   | STEMS
2023-11-08 13:28:41,768 INFO [n0001786#3]       StepMonitoring.java:98   | REDUCTION
2023-11-08 13:30:41,818 WARN [n0001786#3]            SheetStub.java:578  | Timeout 120 seconds for step REDUCTION
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.audiveris.omr.sheet.SheetStub.doOneStep(SheetStub.java:570)
	at org.audiveris.omr.sheet.SheetStub.reachStep(SheetStub.java:1358)
	at org.audiveris.omr.sheet.Book.reachBookStep(Book.java:2023)
	at org.audiveris.omr.sheet.Book.transcribe(Book.java:2577)
	at org.audiveris.omr.sheet.Book.export(Book.java:634)
	at org.audiveris.omr.CLI$ProcessingTask.processBook(CLI.java:887)
	at org.audiveris.omr.CLI$CliTask.call(CLI.java:490)
	at org.audiveris.omr.Main.runBatchTasks(Main.java:363)
	at org.audiveris.omr.Main.main(Main.java:252)
	at Audiveris.main(Audiveris.java:50)
2023-11-08 13:30:41,832 WARN [n0001786#3]                 Book.java:2030 | Error processing stub
2023-11-08 13:30:41,833 INFO [n0001786#3]                 Book.java:2535 | Book{n0001786} storing
2023-11-08 13:30:42,015 INFO [n0001786#3]                 Book.java:2515 | Stored /book.xml
2023-11-08 13:30:42,120 INFO [n0001786#3]           DataHolder.java:348  | Stored /sheet#3/BINARY.png
2023-11-08 13:30:42,933 INFO [n0001786#3]                Sheet.java:1529 | Stored /sheet#3/sheet#3.xml
2023-11-08 13:30:42,933 INFO [n0001786#3]                 Book.java:2476 | Book stored as /home/cher/projects/nota/omr/n0001786/n0001786.omr
2023-11-08 13:30:42,953 INFO [n0001786#3]            SheetStub.java:1605 | Disposed sheet#3
2023-11-08 13:30:43,107 INFO [n0001786#3]                 Book.java:2035 | End of Stub#3 memory: 128,592,632
2023-11-08 13:30:43,108 INFO [n0001786]                Score.java:885  | PartCollation needed in {Score 1}
2023-11-08 13:30:44,864 INFO [n0001786]            SheetStub.java:1044 | Loaded /sheet#2/sheet#2.xml
2023-11-08 13:30:45,675 INFO [n0001786]            SheetStub.java:1044 | Loaded /sheet#3/sheet#3.xml
2023-11-08 13:30:45,862 INFO [n0001786]                 Book.java:2515 | Stored /book.xml
2023-11-08 13:30:46,398 INFO [n0001786]                Sheet.java:1529 | Stored /sheet#2/sheet#2.xml
2023-11-08 13:30:46,821 INFO [n0001786]                Sheet.java:1529 | Stored /sheet#3/sheet#3.xml
2023-11-08 13:30:46,822 INFO [n0001786]                 Book.java:2476 | Book stored as /home/cher/projects/nota/omr/n0001786/n0001786.omr
2023-11-08 13:30:46,833 INFO [n0001786]                Score.java:187  | Closing {Score 1}
```

[n0001786.pdf](https://github.com/Audiveris/audiveris/files/13295824/n0001786.pdf)

**Comment by hbitteur** [comment]
I get the same time-out error when processing your input file on sheet 3 with Audiveris 5.3.1 (Windows installer).
However, using the development version (5.4-alpha), everything is OK.

Could you pull and build on your own using the development branch? (see [this handbook section](https://audiveris.github.io/audiveris/_pages/install/sources/))

**Comment by jenia0jenia** [comment]
I checked with development version (5.4-alpha) and received another an error (

```
> Task :run
INFO  []                       CLI 282  | CLI args: [-batch, -export, -output, /home/cher/projects/nota/omr/n0001786, --, /home/cher/projects/nota/pdf/n0001786.pdf]
INFO  []              TesseractOCR 116  | TESSDATA_PREFIX value: null
WARN  []              TesseractOCR 345  | Tesseract data could not be found. Try setting TESSDATA_PREFIX environment variable to point to tessdata folder.
INFO  []                      Main 402  | Environment:
- Audiveris:    5.4-alpha:6f58c7509
- OS:           Linux 5.10.102.1-microsoft-standard-WSL2
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)
- OCR Engine:   No OCR is available!
INFO  []             AliasPatterns 134  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                      Main 242  | Running in batch mode
INFO  []                      Main 190  | Submitting 1 task(s) in sequence:
    Input "/home/cher/projects/nota/pdf/n0001786.pdf"
```

process log in file 
[n0001786-20231108T1733.log](https://github.com/Audiveris/audiveris/files/13297899/n0001786-20231108T1733.log)
