### ISSUE TITLE
Cannot find freetype in debian

### ISSUE THREAD

**Issue by dosas** [Audiveris/audiveris#82]
OS: 
```
Linux desktop 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
```

Error when loading demo 
```
~/audiveris$ gradle run

> Configure project : 
targetOS=linux-x86_64

> Task :compileJava 
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :run 
LogUtil. Property logback.configurationFile not defined.
LogUtil. No /home/ich/.config/AudiverisLtd/audiveris/logback.xml
LogUtil. Config file:///home/ich/audiveris/res/logback.xml
INFO  []                       CLI 180  | CLI args: []
LogUtil. Logging to /home/ich/.cache/AudiverisLtd/audiveris/log/20180219T213117.log
INFO  []                      Main 338  | Environment:
- Audiveris:    5.0.0:743f229
- OS:           Linux 3.16.0-4-amd64
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01
INFO  []             AliasPatterns 143  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []               Nd4jBackend 194  | Loaded [CpuBackend] backend
INFO  []           NativeOpsHolder 49   | Number of threads used for NativeOps: 2
INFO  []      DefaultOpExecutioner 544  | Backend used: [CPU]; OS: [Linux]
INFO  []      DefaultOpExecutioner 545  | Cores: [4]; Memory: [0.9GB];
INFO  []      DefaultOpExecutioner 546  | Blas vendor: [OPENBLAS]
INFO  []        AbstractClassifier 332  | Classifier data loaded from default uri file:///home/ich/audiveris/res/basic-classifier.zip
WARN  []               Reflections 208  | could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:237)
        at org.reflections.Reflections.scan(Reflections.java:204)
        at org.reflections.Reflections.<init>(Reflections.java:129)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration.registerSubtypes(NeuralNetConfiguration.java:431)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration.configureMapper(NeuralNetConfiguration.java:386)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration.initMapper(NeuralNetConfiguration.java:376)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration.<clinit>(NeuralNetConfiguration.java:123)
        at org.deeplearning4j.nn.conf.MultiLayerConfiguration.fromJson(MultiLayerConfiguration.java:124)
        at org.audiveris.omr.classifier.ModelSystemSerializer.restoreMultiLayerNetwork(ModelSystemSerializer.java:165)
        at org.audiveris.omr.classifier.DeepClassifier.loadModel(DeepClassifier.java:402)
        at org.audiveris.omr.classifier.DeepClassifier.loadModel(DeepClassifier.java:69)
        at org.audiveris.omr.classifier.AbstractClassifier.load(AbstractClassifier.java:323)
        at org.audiveris.omr.classifier.DeepClassifier.<init>(DeepClassifier.java:98)
        at org.audiveris.omr.classifier.DeepClassifier.getInstance(DeepClassifier.java:119)
        at org.audiveris.omr.classifier.ShapeClassifier.getSecondInstance(ShapeClassifier.java:100)
        at org.audiveris.omr.classifier.ShapeClassifier$1.call(ShapeClassifier.java:58)
        at org.audiveris.omr.classifier.ShapeClassifier$1.call(ShapeClassifier.java:50)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
INFO  []        AbstractClassifier 332  | Classifier data loaded from default uri file:///home/ich/audiveris/res/deep-classifier.zip
INFO  [Dichterliebe01]                 BasicBook 427  | 2 sheets in /home/ich/audiveris/data/examples/Dichterliebe01.pdf
WARN  [Dichterliebe01#1]                 BasicStub 841  | Error in LOAD java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.audiveris.omr.sheet.BasicStub.doOneStep(BasicStub.java:824)
        at org.audiveris.omr.sheet.BasicStub.reachStep(BasicStub.java:564)
        at org.audiveris.omr.sheet.ui.StubsController.checkStubStatus(StubsController.java:819)
        at org.audiveris.omr.sheet.ui.StubsController.access$200(StubsController.java:91)
        at org.audiveris.omr.sheet.ui.StubsController$3.call(StubsController.java:508)
        at org.audiveris.omr.sheet.ui.StubsController$3.call(StubsController.java:499)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError: null
        at de.intarsys.pdf.platform.cwt.font.freetype.FreetypeFontFactory.getLibrary(FreetypeFontFactory.java:64)
        at de.intarsys.pdf.platform.cwt.font.freetype.FreetypeFontFactory.createPlatformFont(FreetypeFontFactory.java:135)
        at de.intarsys.pdf.platform.cwt.rendering.CSPlatformDevice.textSetFont(CSPlatformDevice.java:755)
        at de.intarsys.pdf.content.CSDeviceBasedInterpreter.render_Tf(CSDeviceBasedInterpreter.java:762)
        at de.intarsys.pdf.content.CSInterpreter.process(CSInterpreter.java:238)
        at de.intarsys.pdf.content.CSInterpreter.process(CSInterpreter.java:206)
        at de.intarsys.pdf.content.CSDeviceBasedInterpreter.process(CSDeviceBasedInterpreter.java:195)
        at org.audiveris.omr.image.ImageLoading$JPodLoader.getImage(ImageLoading.java:462)
        at org.audiveris.omr.sheet.BasicBook.loadSheetImage(BasicBook.java:910)
        at org.audiveris.omr.step.LoadStep.doit(LoadStep.java:71)
        at org.audiveris.omr.step.Step.doit(Step.java:168)
        at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:814)
        at org.audiveris.omr.sheet.BasicStub$3.call(BasicStub.java:802)
        ... 4 common frames omitted
Caused by: java.lang.NullPointerException: no native interface available
        at de.intarsys.nativec.api.NativeInterface.set(NativeInterface.java:104)
        at de.intarsys.nativec.api.NativeInterface.get(NativeInterface.java:93)
        at de.intarsys.cwt.freetype.nativec._FTNI.init(_FTNI.java:127)
        at de.intarsys.cwt.freetype.nativec._FTNI.<init>(_FTNI.java:88)
        at de.intarsys.cwt.freetype.Freetype.<clinit>(Freetype.java:99)
        ... 17 common frames omitted
INFO  [Dichterliebe01#1]                 BasicStub 846  | Cause java.lang.ExceptionInInitializerError
INFO  [Dichterliebe01#1]                 BasicStub 571  | StepException detected in [LOAD, BINARY]
```

And  yes freetype is installed
```
$ file /usr/lib/x86_64-linux-gnu/libfreetype.so.6
/usr/lib/x86_64-linux-gnu/libfreetype.so.6: symbolic link to libfreetype.so.6.11.1
```

On branch master:
```
743f229a9cff28ebdecb26312e62f6413f772e1d
```

**Comment by maximumspatium** [comment]
Did you try `libfreetype6-dev`?

**Comment by dosas** [comment]
```
aptitude search libfreetype
i   libfreetype6                                                                                                   - FreeType 2 font engine, shared library files                                                                            
i A libfreetype6:i386                                                                                              - FreeType 2 font engine, shared library files                                                                            
i   libfreetype6-dev                                                                                               - FreeType 2 font engine, development files                                                                               
p   libfreetype6-dev:i386
```

**Comment by maximumspatium** [comment]
Please run `java -XshowSettings:properties` in your terminal and post the result here.

**Comment by dosas** [comment]
```
 java -XshowSettings:propertie
VM settings:
    Max. Heap Size (Estimated): 1.73G
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM

Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    file.encoding = UTF-8
    file.encoding.pkg = sun.io
    file.separator = /
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path = .
    java.class.version = 52.0
    java.endorsed.dirs = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed
    java.ext.dirs = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext
        /usr/java/packages/lib/ext
    java.home = /usr/lib/jvm/java-8-openjdk-amd64/jre
    java.io.tmpdir = /tmp
    java.library.path = /usr/java/packages/lib/amd64
        /usr/lib/x86_64-linux-gnu/jni
        /lib/x86_64-linux-gnu
        /usr/lib/x86_64-linux-gnu
        /usr/lib/jni
        /lib
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.8.0_131-8u131-b11-1~bpo8+1-b11
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_131
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.131-b11
    line.separator = \n 
    os.arch = amd64
    os.name = Linux
    os.version = 3.16.0-4-amd64
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.class.path = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar
        /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
        /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar
        /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar
        /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar
        /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar
        /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar
        /usr/lib/jvm/java-8-openjdk-amd64/jre/classes
    sun.boot.library.path = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
    sun.cpu.endian = little
    sun.cpu.isalist = 
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = UTF-8
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level = unknown
    user.country = US
    user.dir = /home/ich/audiveris
    user.home = /home/ich
    user.language = en
    user.name = ich
    user.timezone = 

Locale settings:
    default locale = English
    default display locale = English (United States)
    default format locale = English (United States)
    available locales = , ar, ar_AE, ar_BH, ar_DZ, ar_EG, ar_IQ, ar_JO, 
        ar_KW, ar_LB, ar_LY, ar_MA, ar_OM, ar_QA, ar_SA, ar_SD, 
        ar_SY, ar_TN, ar_YE, be, be_BY, bg, bg_BG, ca, 
        ca_ES, cs, cs_CZ, da, da_DK, de, de_AT, de_CH, 
        de_DE, de_GR, de_LU, el, el_CY, el_GR, en, en_AU, 
        en_CA, en_GB, en_IE, en_IN, en_MT, en_NZ, en_PH, en_SG, 
        en_US, en_ZA, es, es_AR, es_BO, es_CL, es_CO, es_CR, 
        es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, 
        es_PA, es_PE, es_PR, es_PY, es_SV, es_US, es_UY, es_VE, 
        et, et_EE, fi, fi_FI, fr, fr_BE, fr_CA, fr_CH, 
        fr_FR, fr_LU, ga, ga_IE, hi, hi_IN, hr, hr_HR, 
        hu, hu_HU, in, in_ID, is, is_IS, it, it_CH, 
        it_IT, iw, iw_IL, ja, ja_JP, ja_JP_JP_#u-ca-japanese, ko, ko_KR, 
        lt, lt_LT, lv, lv_LV, mk, mk_MK, ms, ms_MY, 
        mt, mt_MT, nl, nl_BE, nl_NL, no, no_NO, no_NO_NY, 
        pl, pl_PL, pt, pt_BR, pt_PT, ro, ro_RO, ru, 
        ru_RU, sk, sk_SK, sl, sl_SI, sq, sq_AL, sr, 
        sr_BA, sr_BA_#Latn, sr_CS, sr_ME, sr_ME_#Latn, sr_RS, sr_RS_#Latn, sr__#Latn, 
        sv, sv_SE, th, th_TH, th_TH_TH_#u-nu-thai, tr, tr_TR, uk, 
        uk_UA, vi, vi_VN, zh, zh_CN, zh_HK, zh_SG, zh_TW
        
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -server	  to select the "server" VM
    -zero	  to select the "zero" VM
    -dcevm	  to select the "dcevm" VM
                  The default VM is server,
                  because you are running on a server-class machine.


    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
```

**Comment by maximumspatium** [comment]
Your JDK is `amd64` but libfreetype is `i386`. Looks like an arch conflict...
And you may consider an upgrade of your oldish JDK 131 to the latest one (152).

**Comment by dosas** [comment]
file /usr/lib/x86_64-linux-gnu/libfreetype.so.6 seems like 64 to me?
or is it a problem that the package for i386 is alos installed?

**Comment by maximumspatium** [comment]
> or is it a problem that the package for i386 is also installed?
It may be a problem, see [here](http://forums.debian.net/viewtopic.php?f=6&t=110052)
I'd deinstall i386 packages and try again.

**Comment by dosas** [comment]
Okay i think i fucked up my system. Java and linux just don't like each other.
I will just try to convert the pdf to a png ...

**Comment by maximumspatium** [comment]
Did `uninstall libfreetype:i386` work? I think it should be quite difficult to screw up Debian...

**Comment by dosas** [comment]
i   libfreetype6                                                                                                   - FreeType 2 font engine, shared library files                                                                            
p   libfreetype6:i386                                                                                              - FreeType 2 font engine, shared library files                                                                            
iB  libfreetype6-dev                                                                                               - FreeType 2 font engine, development files                                                                               
pB  libfreetype6-dev:i386

**Comment by maximumspatium** [comment]
"B"-suffix in the above mentioned lines (iB/pB) means broken packages or dependencies. What does
`dpkg --audit libfreetype6` say?

**Comment by dosas** [comment]
it just returns 0

**Comment by maximumspatium** [comment]
BTW, it would worth it to uninstall `libfreetype6-dev` first followed by a repair attempt for `libfreetype6`.

**Comment by maximumspatium** [comment]
Another hint: find out which package requires `libfreetype6:i386`. Maybe Wine?

**Comment by dosas** [comment]
```
aptitude search libfreetype
i   libfreetype6                                                                                                   - FreeType 2 font engine, shared library files                                                                            
p   libfreetype6:i386                                                                                              - FreeType 2 font engine, shared library files                                                                            
i   libfreetype6-dev                                                                                               - FreeType 2 font engine, development files                                                                               
p   libfreetype6-dev:i386
```

okay that seems to work but i still get the same freetype exception as in the original issue.

**Comment by maximumspatium** [comment]
> okay that seems to work but i still get the same freetype exception as in the original issue.

What's the output of the following commands?
```
dpkg --print-architecture
dpkg --print-foreign-architectures
```

**Comment by maximumspatium** [comment]
One more hint: `sudo apt-get --only-upgrade install openjdk-8-jdk`

**Comment by maximumspatium** [comment]
Your issue is certainly related to the specific Linux distribution, not to Audiveris project. You are so far the first user that reported an issue with freetype on Linux.
I did my best to assist you in troubleshooting but I'm out of my depth now. You'd be better off asking on a Debian forum for further assistance. I therefore close this issue for the moment being. Feel free to reopen it if you need further assistance.

**Comment by dosas** [comment]
$ dpkg --print-architecture
amd64
$ dpkg --print-foreign-architectures
i386

**Comment by maximumspatium** [comment]
Well, it looks good so far. Did you try to ask on a Debian forum for a solution? I'm unfortunately not a Debian expert. I must admit I never encountered any issues with freetype on my Linux boxes (Ubuntu, Opensuse and Fedora). As I said, I'm out of my depth. Sorry!
